### PR TITLE
Mark GC.addRoot and GC.removeRoot as @nogc

### PR DESCRIPTION
**Pull request by Philpax**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Please update [gcstub](https://github.com/D-Programming-Language/druntime/blob/master/src/gcstub/gc.d) as well.

**Comment by Philpax** [comment]
I would have, but the commit that added `@nogc` to `addRange` didn't update those: https://github.com/D-Programming-Language/druntime/commit/db7fe0eb9d3af3154d1873380b00853c7b977c81

Should I update gcstub/proxy for both addRoot and addRange?

**Comment by DmitryOlshansky** [comment]
Seems to fallen through cracks. I guess this needs to update gcstub and proxy for both add/remove ranges

**Comment by MartinNowak** [comment]
Going to merge this anyhow, whoever uses gcstub next can update it.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by leandro-lucarella-sociomantic** [comment]
Stupid question, shouldn't it be all the code in the GC @nogc? :)

It happened to me in the past that I used `assert()` in the GC, which triggered an allocation, which called GC code and you can imagine what happened next...

**Comment by schveiguy** [comment]
@leandro-lucarella-sociomantic I think we have to mark public API as not `@nogc`. Otherwise direct calls to GC.malloc would be `@nogc`!

**Pull request merged**
