### PR TITLE
core/threadasm.S: Split up per target and move to core/internal/threadasm

### PR DESCRIPTION
**Pull request by ibuclaw**
GDC is able to compile the correct source based on what's determined at configure-time.

Can LDC do the same? Ping @kinke / @redstar

### CODE REVIEW

**Comment by kinke** [comment]
Sure; it'll require some CMake fiddling though.

**Comment by joakim-noah** [comment]
Is it possible to move these to D? It'd be nice to get rid of the C compiler requirement to build the stdlib, at least as an option. `errno.c` is not even used by druntime anymore, by default. If we make `etc.c.zlib` optional, we could try to have a build option that only uses the D compiler.

**Comment by ibuclaw** [comment]
@klickverbot - I removed one layer of ifdef's, so you'll still need e.g:
```
#if defined( __PPC64__ )
#include "core/internal/threadasm/powerpc64.S"
#endif
```
But yes, in principle you could do that.

Actually, there's a further refactoring to be done, move the header definitions into a common asm file.

**Comment by ibuclaw** [comment]
> Actually, there's a further refactoring to be done, move the header definitions into a common asm file.

Done and rebased.

**Comment by thewilsonator** [comment]
Needs another rebase but otherwise looks fine to me.

**Comment by Geod24** [comment]
Druntime have been merged into DMD. Please re-submit your PR to `dlang/dmd` repository.

**Pull request closed without merging**
