### PR TITLE
Fix issue 19177: add clock() and CLOCKS_PER_SEC for Solaris

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by ZombineDev** [comment]
I'll rebase your PR to stable, so it can be included in the upcoming release.

**Comment by ZombineDev** [comment]
@thewilsonator I don't have write access to your repo, so you can either give me access or do those commands manually:
```
git checkout master
git pull upstream master --ff-only

git checkout stable
git pull upstream stable --ff-only

git rebase --onto stable master patch-3
```

**Comment by ZombineDev** [comment]
Closing in favor of https://github.com/dlang/druntime/pull/2288.

**Comment by Geod24** [comment]
@thewilsonator : You can just use `git remote add dlang https://github.com/dlang/druntime.git` and then `git rebase --onto dlang/stable master patch-3` (replace `master` with the branch you used as base for `patch-3`).

**Pull request closed without merging**
