### PR TITLE
Fix Issue 20629 - atomicStore does not compile for struct using -m64

### PR DESCRIPTION
**Pull request by MoonlightSentinel**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
> This is a regression. Please target stable.

Sorry, I'll rebase once the CI is done.

**Comment by thewilsonator** [comment]
The rebase will restart the CI anyway, you may as well change it now.

**Comment by MoonlightSentinel** [comment]
Done

**Comment by thewilsonator** [comment]
Thanks!

**Comment by MoonlightSentinel** [comment]
auto-merge won't work because #2970 is not in stable yet.

Question from the newsgroup:
Will this be included in the new release?

**Comment by thewilsonator** [comment]
Yes.

**Pull request merged**
