### PR TITLE
Revert "Add SO_REUSEPORT constant"

### PR DESCRIPTION
**Pull request by wilzbach**
Temporarily reverts dlang/druntime#1879

Allows the Project Tester (and other projects that test `dmd-nightly`) to be green. We can revert the revert and keep it in the queue until this has been fixed at the projects. As a general policy Jenkins (the project tester) should always be green.

CC @CyberShadow

### CODE REVIEW

**Comment by CyberShadow** [comment]
Can we make Jenkins required again after htis?

**Comment by wilzbach** [comment]
> Can we make Jenkins required again after this?

That was the idea - Martin has worked quite a bit on making it more stable, so we should give it a try again ;-)

**Comment by Burgos** [comment]
Looks like Jenkins can't handle "GitHub" reverts since it tries to find a matching branch in dmd/phobos/dub/et al.: https://ci.dlang.io/job/dlang-org/job/druntime/job/revert-1879-soreusse/

**Comment by Burgos** [comment]
https://github.com/dlang/ci/issues/56

**Comment by Burgos** [comment]
Looks like autotester fails for an unrelated reason: https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=2&pullid=1885 https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2677274&isPull=true

**Comment by MartinNowak** [comment]
> Can we make Jenkins required again after this?

We also have a new feature, you can now login to https://ci.dlang.io/ with your Github account and should be able to replay tests (see https://github.com/dlang/ci/pull/36).

When you click on the linked jenkins status here in GH, the login button is a bit hidden (trying to change that with https://github.com/jenkinsci/blueocean-plugin/pull/1260).
For example going to https://ci.dlang.io/job/dlang-org/job/druntime/job/PR-1886/1/display/redirect,
click on the `x`
x
to close the overlayed result page, then you should see a login button in the normal header.
login

**Comment by CyberShadow** [comment]
Sigh, Phobos master is failing Jenkins...
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/master/270/pipeline/

**Pull request merged**
