### PR TITLE
remove emulated TLS for OSX

### PR DESCRIPTION
**Pull request by MartinNowak**
- native TLS supported since 2.072.0

### CODE REVIEW

**Comment by ZombineDev** [comment]
CyberShadow/DAutoTest fails due to https://github.com/dlang/dlang.org/pull/1796.

**Comment by jacob-carlborg** [comment]
@MartinNowak 32bit is still using emulated TLS (unless someone recently changed that).

**Comment by MartinNowak** [comment]
Yes, smelled a bit as if 32-bit was still relying on this. Any reference to the OSX TLS implementation? Can't find any in https://github.com/dlang/dmd/pull/5346, but I guess you didn't reverse engineer all of it @jacob-carlborg.
I found https://stackoverflow.com/a/29929949/2371032 which mentions TLS support in XCode 8.

**Comment by MartinNowak** [comment]
> Decide what to do about OSX 32bit.

Keep as long as it's not much to keep.

**Comment by jacob-carlborg** [comment]
> Any reference to the OSX TLS implementation? 

There's no official reference, as far as I know. What I found out is documented here [1][2].

[1] https://github.com/dlang/dmd/blob/master/src/ddmd/toobj.d#L1212
[2] https://github.com/dlang/dmd/blob/master/src/ddmd/backend/el.c#L1285

**Comment by jacob-carlborg** [comment]
TLS was supported before Xcode 8. `__thread` was supported but not `thread_local`, IIRC.

**Comment by MartinNowak** [comment]
> There's no official reference, as far as I know. What I found out is documented here [1][2].

Unfortunately doesn't document from what you derived this. Guess from their runtime linker and llvm/clang, right?

**Comment by jacob-carlborg** [comment]
> Unfortunately doesn't document from what you derived this. Guess from their runtime linker and llvm/clang, right?

From dyld and looking at the assembly and object dumps from Clang.

**Comment by ZombineDev** [comment]
Darwin_64_32 fails consistently on autotester, so it looks we can't move forward with this PR. Please reopen, if I'm misunderstanding.

**Pull request closed without merging**
