### PR TITLE
[stable] On OpenBSD and Android make core.sys.posix.arpa.inet: htonl, htons, ntohl, & ntohs work correctly on big endian architectures

### PR DESCRIPTION
**Pull request by n8sh**
~~This PR also changes the linkage of those functions from C to D when we're defining them in D runtime.~~

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Where is the extern(C)?

**Comment by n8sh** [comment]
>Where is the extern(C)?

On line 31:
https://github.com/dlang/druntime/blob/0cfc798bdb93f33b8bc0cfc60309742c2ddfdbe3/src/core/sys/posix/arpa/inet.d#L31

**Comment by ibuclaw** [comment]
> >Where is the extern(C)?
> 
> On line 31:
> https://github.com/dlang/druntime/blob/0cfc798bdb93f33b8bc0cfc60309742c2ddfdbe3/src/core/sys/posix/arpa/inet.d#L31

That doesn't affect these functions so the question still stands.

AFAICT, you've added `nothrow @nogc`, but I'd have thought that these would be already present at the top of the file.

**Comment by n8sh** [comment]
My mistake, I misread the closing brace on https://github.com/dlang/druntime/blob/0cfc798bdb93f33b8bc0cfc60309742c2ddfdbe3/src/core/sys/posix/arpa/inet.d#L179 as closing https://github.com/dlang/druntime/blob/0cfc798bdb93f33b8bc0cfc60309742c2ddfdbe3/src/core/sys/posix/arpa/inet.d#L163-L164. I'll force push to remove the erroneous commit message.

**Review by ibuclaw — APPROVED** [review]
Danke schön.

**Pull request merged**
