### PR TITLE
fix issue 15393 - Debug versions in GC code doesn't compile.

### PR DESCRIPTION
**Pull request by rainers**
also fixes freeze in invariant()

### CODE REVIEW

**Comment by thewilsonator** [comment]
Looks good, please squash.

**Comment by rainers** [comment]
> Looks good, please squash.

Will do, but I'm still trying to figure out why "logging.exe" fails to execute by make while it works for all other test files and also works locally and on AppVeyor.

**Comment by rainers** [comment]
BTW: testing on Windows has almost come to a grinding halt. @braddr What happend to the fastest build host "power" that seems to be idling for more than 10 days now?

**Comment by rainers** [comment]
> logging.exe Error: 'logging.exe' not found

I suspect make is confused by finding the file elsewhere in PATH. Using `.\logging.exe` seems to help.

I have also added a fix for the sentinel code that can trigger spurious failures, e.g. https://circleci.com/gh/dlang/druntime/3534?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by thewilsonator** [comment]
Appveyor:
```
Error: 'make' not found
```

**Comment by wilzbach** [comment]
> > Error: 'make' not found
> 
> Grrr. This seems to be the generic error message that DM make produces for negative results from the invoked command (memstomp crashed).

Yeah it's more than time to replace the old & super-fragile DM Make system with sth. like `run.d` which replaced DMD's test system (or build.d which replaces DMD's build files).

**Comment by rainers** [comment]
> memstomp crashed

A bug in the untested memstomp-code of https://github.com/dlang/druntime/pull/2430

**Pull request merged**
