### PR TITLE
object: Declare private struct AA and fix aaA function signatures

### PR DESCRIPTION
**Pull request by ibuclaw**
All AA tests currently SEGV on 32-bit Solaris/SPARC,

Closer investigation reveals object.d calls _aaValues (and _aaKeys) incorrectly:

While the implementation expects a struct AA

libdruntime/rt/aaA.d:
```
extern (C) inout(void[]) _aaValues(inout AA aa, in size_t keysz, in size_t valsz,
```

the call passes a void * instead in libdruntime/object.d:
```
inout(void)[] _aaValues(inout void* p, in size_t keysize, in size_t valuesize, const TypeInfo tiValArray) pure nothrow;
...
auto a = cast(void[])_aaValues(cast(inout(void)*)aa, Key.sizeof, Value.sizeof, typeid(Value[]));
```

The problem is that on 32-bit SPARC small structs are passed by reference, so there's a mismatch between caller and callee.

On 64-bit SPARC instead, they are passed by value, so the mismatch doesn't matter and the tests PASS.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Alternatively, this could be fixed the other way around.  Have the signatures in _aaA.d changed to match object.d.

**Comment by wilzbach** [comment]
CC @CyberShadow as are fails with this.

**Comment by CyberShadow** [comment]
Looking at it, I don't see any reason to believe this is anything but a genuine regression... @ibuclaw Maybe you have some ideas. I will run a reduction, but it will take a while.

**Comment by CyberShadow** [comment]
@ibuclaw I reduced it to the following:

```d
struct S
{
	string fileName;
	void[][string] cachedData;
	alias cachedData this;
}

unittest
{
	auto s = S("a");
	assert(s.keys.length == 0);
}
```

This segfaults for me with your patch.

**Comment by ibuclaw** [comment]
@CyberShadow - thanks, I'll add that to the druntime unittests.

**Comment by ibuclaw** [comment]
I think the problem is _aaRange needs updating too.

**Comment by ibuclaw** [comment]
@CyberShadow 's bug has been addressed.

**Pull request merged**
