### PR TITLE
Musl: add missing declarations needed for vibe.d

### PR DESCRIPTION
**Pull request by joakim-noah**
Looks like the Musl port was done a bit sloppily, I needed these to build the `vibe-d` package with dub.

### CODE REVIEW

**Comment by joakim-noah** [comment]
ping, @ibuclaw.

**Comment by joakim-noah** [comment]
@CyberShadow, @yshui got a lot of it ported, I've added a bit too. Most of the tests pass, see dlang/dmd#8020 for more info.

**Comment by yshui** [comment]
@CyberShadow was that not in the ChangeLog?

**Comment by CyberShadow** [comment]
@yshui Thanks! Sorry, I haven't been following them.

**Pull request merged**
