### PR TITLE
Fix Issue 18942 - core.internal.hash can take advantage of alignment info on non-x86

### PR DESCRIPTION
**Pull request by n8sh**
On machines that do not support unaligned memory access, `core.internal.hash` can use statically available alignment information to determine when `uint` reads can be used.

### CODE REVIEW

**Comment by n8sh** [comment]
This code that disables unaligned reads with DMD is from the original 2013 commit. Maybe the original reason (whatever it was) no longer applies.

```d
version(AnyX86)
{
    version(DigitalMars)
    {
    }
    else
    {
        version = HasUnalignedOps;
    }
}
```

This code and the comment about some kind of inlining bug also dates back to the original 2013 commit.
```d
        //Compiler can optimize this code to simple *cast(uint*)x if it possible.
        version(HasUnalignedOps)
        {
            if (!__ctfe)
                return *cast(uint*)x; //BUG: Can't be inlined by DMD
        }
```

**Comment by n8sh** [comment]
The above-mentioned code indeed was outdated, so I've made PR https://github.com/dlang/druntime/pull/2210 to remove it.

**Comment by n8sh** [comment]
Revised to remove unnecessary uses of `version(HasUnalignedOps)` which would be removed anyway by PR https://github.com/dlang/druntime/pull/2209.

**Comment by wilzbach** [comment]
@n8sh FYI - rebased this for you.

**Pull request merged**
