### PR TITLE
Cirrus CI: Add FreeBSD 11 pipeline

### PR DESCRIPTION
**Pull request by ibuclaw**
~This in the hope to avoid accidental regressions such as #3546~

Dependent fix now moved to dlang/dmd#12985

### CODE REVIEW

**Comment by ibuclaw** [comment]
FreeBSD 11 pipelines fail as expected: https://cirrus-ci.com/task/5910778206224384

**Comment by ibuclaw** [comment]
Re-running FreeBSD11 with the most recent compiler release that it can tolerate.

**Comment by ibuclaw** [comment]
This is blocked until #3546 is merged.

**Comment by ibuclaw** [comment]
Re-basing on top of the dependant PR early to prove that the issue goes away.

**Comment by ibuclaw** [comment]
Should be unblocked now.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
