### PR TITLE
Fix issue 22210 - Partially revert #3459 and #3463

### PR DESCRIPTION
**Pull request by tom-tan**
This request fixes the regression (issue 22210) by reverting fe4556f (#3459) and 406e51c (#3463).
It also adds a unit test for issue  22210.

### CODE REVIEW

**Comment by ibuclaw** [comment]
If this is regression made it to release, then please target stable branch.

**Comment by tom-tan** [comment]
Thank you for your advice.
I changed the target branch to `stable` because it was introduced since 2.097.0 release.

**Comment by CyberShadow** [comment]
You need to also rebase your commits on the stable branch and force-push.

Could the test be a unit test in the respective module, instead of an external test?

**Comment by RazvanN7** [comment]
cc @andralex and @nordlow

**Comment by nordlow** [comment]
Note that

```d
import std.meta : allSatisfy;

enum isHashable(T) = __traits(compiles, () { T.init; } );

class C
{
    static if (allSatisfy!(isHashable, int, B)) {}
}

class A
{
    static if (isHashable!B) {}
}

class B
{
    static if (isHashable!C) {}
}
```

compiles.

**Comment by tom-tan** [comment]
As mentioned in issue 22210, the source of this problem is issue 20443.
This request is a workaround until issue 20443 is solved.

**Comment by andralex** [comment]
Took a look into this, didn't find a suitable workaround on the library side. Reverting the any/allSatisfy changes is not a problem, the new code just eliminated the awkward idiom "has the result already been defined yet".

The `maxAlignment` revert is more problematic because the old code is recursive. Can we leave it in place? It does not seem to be prey to the issue.

Last but not least, the issue of forward reference is definitely important. @tom-tan please advise if you can leave `maxAlignment` in place. Thanks.

**Comment by tom-tan** [comment]
> please advise if you can leave `maxAlignment` in place.

It is OK for me to leave it in place.
Can I update the request to revert only `allSatisfy` and `anySatisfy`?

**Comment by andralex** [comment]
> > please advise if you can leave `maxAlignment` in place.
> 
> It is OK for me to leave it in place. Can I update the request to revert only `allSatisfy` and `anySatisfy`?

Yes, please. Thanks!

**Comment by tom-tan** [comment]
Done!

**Review by andralex — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by tom-tan** [comment]
Thanks!

**Pull request merged**
