### PR TITLE
Fix Issue 18828 - [-betterC] helpless error in object.d

### PR DESCRIPTION
**Pull request by JinShil**
I don't really like this fix, but I'm not sure how else to do it, and maybe this PR will elicit some ideas from others.

### CODE REVIEW

**Comment by JinShil** [comment]
I'm not sure how to test -betterC in the runtime, so, instead, I added a test at https://github.com/dlang/dmd/pull/8235

**Comment by jacob-carlborg** [comment]
Is this testable?

**Comment by JinShil** [comment]
> Is this testable? 

Yes, at https://github.com/dlang/dmd/pull/8235.  I didn't know how else to do it.

**Comment by jacob-carlborg** [comment]
Not sure about how much work it would be, but what about adding a new directory here: https://github.com/dlang/druntime/tree/master/test ?

**Comment by JinShil** [comment]
I added the directory and test to the best of my ability, but I don't even understand what most of the syntax in the Makefile is for and I'm not even sure if the test is running.

**Comment by RazvanN7** [comment]
Can we close : https://github.com/dlang/dmd/pull/8235 now ?

**Comment by schveiguy** [comment]
Haha, I just went into bugzilla to make a new issue about the inefficiency of destroy, to find that the code I *swore* was using `typeid` is no longer there. And lo and behold, it's changed, but for another reason.

I'm still going to file an issue, because I feel like smaller structs can be done much more efficiently than casting to ubyte arrays. But this change helps significantly.

See: https://forum.dlang.org/post/pe3pcp$13t4$1@digitalmars.com

**Comment by schveiguy** [comment]
> I'm still going to file an issue

See https://issues.dlang.org/show_bug.cgi?id=18899

**Pull request merged**
