### PR TITLE
Fix range violation in multithreaded application compiled with -profile=gc option

### PR DESCRIPTION
**Pull request by japplegame**
Possible related issue https://issues.dlang.org/show_bug.cgi?id=14511

### CODE REVIEW

**Comment by JackStouffer** [comment]
Please follow the [D style guide](https://dlang.org/dstyle.html)

**Comment by UplinkCoder** [comment]
This will not fix anything in the long run.
The range violation happens because of race-conditions.
You would have to use a Mutex.

**Comment by japplegame** [comment]
No. The range violation happens because of wrong merging several TLS arrays into one. There is no race conditions and no need of additional mutexes, because the code is already synchronized, see [line 90](https://github.com/japplegame/druntime/blob/a6f139313b612223c2b035bd22abd9a7cd4503d1/src/rt/profilegc.d#L90)

**Comment by japplegame** [comment]
Ping

**Pull request closed without merging**
