### PR TITLE
 Add musl libc definitions to:  src_core_thread

### PR DESCRIPTION
**Pull request by yshui**
Splitted from #1997

### CODE REVIEW

**Comment by joakim-noah** [comment]
No need for a separate pull for every file, a good way to split it is three pulls, like the recent DragonFlyBSD pulls.  I'll look at these file pulls for now- small is fine- but for the rest of your original pull, splitting it like the DragonFly pull is a good idea.

**Comment by yshui** [comment]
> No need for a separate pull for every file

@joakim-noah I already did...

**Comment by joakim-noah** [comment]
Yes, you already split it by file for _some_ of your original massive pull #1997, but for the rest, please just split it in two, not every file by itself.

**Comment by wilzbach** [comment]
Rebased to master fix the CircleCi & DAutoTest failures.

**Comment by ibuclaw** [comment]
All these are just additions and look reasonable to me. One pull request per package (core.stdc, core.sys, etc)  is the usual thing to do for ease of review.

**Comment by yshui** [comment]
@ibuclaw @joakim-noah So it's ok to submit one PR per module?

**Comment by wilzbach** [comment]
Yes, your initial PR was just a bit too large to be reviewed in one piece.

**Comment by ibuclaw** [comment]
@yshui - Yes, of course its fine, although 4 PRs would have been fine also.  One for `core/stdc/*`, one for `core/sys/*`, one for the rest of `core/*`, and one for `rt/*`.

**Comment by joakim-noah** [comment]
One pull per module is way too small for changes like this, please just remove all these merged patches from your original pull #1997 and we'll get that reduced patch in.

**Comment by yshui** [comment]
@joakim-noah OK. I'm just waiting for all the submitted patches to merge before submitting the rest

**Comment by joakim-noah** [comment]
No, don't submit the rest separately.  Just trim down #1997 of the parts that were already merged, and we'll get that first pull in.

**Comment by yshui** [comment]
@joakim-noah I meant to say that I'll submit the rest splitted into 4 parts after the outstanding PRs are merged.

**Comment by joakim-noah** [comment]
If you like, but simply removing these merged patches from #1997 should be enough to get that one in.

**Pull request merged**
