### PR TITLE
fix Issue 11666: Separate platform support into separate files

### PR DESCRIPTION
**Pull request by WalterBright**
Another reboot of https://github.com/D-Programming-Language/druntime/pull/741 and https://github.com/D-Programming-Language/druntime/pull/731

Hopefully this one will merge.

### CODE REVIEW

**Comment by andralex** [comment]
@WalterBright could you please revisit this. We're on the verge of the next DConf... let's either rebase and make this work, or close this. Thanks!

**Comment by MartinNowak** [comment]
For a second module #1255 we didn't see much benefit in splitting the files.

**Comment by DmitryOlshansky** [comment]
Seems stuck - closing? @WalterBright @MartinNowak

**Comment by andralex** [comment]
@WalterBright rebase & revisit

**Comment by DmitryOlshansky** [comment]
Feel free to redo it but it's just sitting in a broken state

**Pull request closed without merging**
