### PR TITLE
core.stdc.stdint: fix mistake with int_fast16_t

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by braddr** [comment]
Can you point to where you find fast16 defined to be short?  Just checked a x86/64 system's stdint.h

#if __WORDSIZE == 64
typedef long int                int_fast16_t;
typedef long int                int_fast32_t;
typedef long int                int_fast64_t;
#else
typedef int                     int_fast16_t;
typedef int                     int_fast32_t;
__extension__
typedef long long int           int_fast64_t;
#endif

the fast* typedefs are explicitly intended to be allowed to map to a larger size if it's generally faster than the exact size.

**Comment by braddr** [comment]
Sorry, just checked explicitly on an osx box, and for some reason they didn't promote up to a full 32bit size.  Strange.  Added auto-merge back.

**Comment by WalterBright** [comment]
On my mac mini:
```
~/tmp> grep fast16_t /usr/include/stdint.h
typedef int16_t          int_fast16_t;
typedef uint16_t        uint_fast16_t;
```
My test program:
```
#include <stdint.h>

extern "C++"
{

void int8(int8_t i) { }
void uint8(uint8_t i) { }

void int16(int16_t i) { }
void uint16(uint16_t i) { }

void int32(int32_t i) { }
void uint32(uint32_t i) { }

void int64(int64_t i) { }
void uint64(uint64_t i) { }

void int_least8(int_least8_t i) { }
void uint_least8(uint_least8_t i) { }

void int_least16(int_least16_t i) { }
void uint_least16(uint_least16_t i) { }

void int_least32(int_least32_t i) { }
void uint_least32(uint_least32_t i) { }

void int_least64(int_least64_t i) { }
void uint_least64(uint_least64_t i) { }

void int_fast8(int_fast8_t i) { }
void uint_fast8(uint_fast8_t i) { }

void int_fast16(int_fast16_t i) { }
void uint_fast16(uint_fast16_t i) { }

void int_fast32(int_fast32_t i) { }
void uint_fast32(uint_fast32_t i) { }

void int_fast64(int_fast64_t i) { }
void uint_fast64(uint_fast64_t i) { }

void intptr(intptr_t i) { }
void uintptr(uintptr_t i) { }

void intmax(intmax_t i) { }
void uintmax(uintmax_t i) { }

}
```
Compiling it,
```
~/tmp> cc -c teststdint.cpp
~/tmp> obj2asm teststdint.o >log32
~/tmp> grep fast16 log32
        public  __Z10int_fast16s
        public  __Z10int_fast16s.eh
        public  __Z11uint_fast16t
        public  __Z11uint_fast16t.eh
__Z10int_fast16s:
__Z11uint_fast16t:
__Z10int_fast16s.eh:
__Z11uint_fast16t.eh:
```
the `s` mangling means `int`.

**Comment by WalterBright** [comment]
> Strange.

Ours is not to reason why, ours is to be compatible or die.

**Pull request merged**
