### PR TITLE
try using dmd's azure-pipeline

### PR DESCRIPTION
**Pull request by rainers**
Will need some adaptions in dmd's files...

### CODE REVIEW

**Comment by rainers** [comment]
Using YAML templates from another repo doesn't seem to work, as they are read before any command is executed. Calling bash/cmd instead needs a bit more duplication, but with https://github.com/dlang/dmd/pull/10421 it should be rather small.

This PR could work with the dmd PR, but is currently only using dmd master (the first two jobs passed on a personal pipeline).

@wilzbach Can you enable azure for druntime?

**Comment by rainers** [comment]
BTW: here is the azure run on my account: https://rainers8.visualstudio.com/druntime/_build/results?buildId=20

**Comment by thewilsonator** [comment]
@wilzbach ping

**Comment by wilzbach** [comment]
Sorry, added it to Azure. thanks a lot @rainers! I also sent out an invite to the dlanguage Azure group to you in case access is required again in the future!

**Comment by wilzbach** [comment]
FYI: I also configured Azure Pipelines for Phobos and tools in case it comes ever up as I presume we can do a similar PR to Phobos once this is passing.

**Comment by rainers** [comment]
> I also sent out an invite to the dlanguage Azure group to you in case access is required again in the future!

Thanks, but it seems that went to the wrong account. My MS account is rainers8 at hotmail dot com.

**Comment by rainers** [comment]
> Will need some adaptions in dmd's files...

It needs https://github.com/dlang/dmd/pull/10421

**Pull request merged**
