### PR TITLE
add codecov configuration to disable comments

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
LGTM, afaik the codecov.yml is only applied from the master branch, not the PR branch. Should I send similar prs to dmd and Phobos?

**Comment by MartinNowak** [comment]
Still trying to figure out why the GH status doesn't show.

**Comment by wilzbach** [comment]
> Still trying to figure out why the GH status doesn't show.

Afaik @CodeCov waits until all configured CI pass (DAutoTest and auto-tester are not included) and then sends the coverage information to Github via their status API. That's why you don't need to enable it as a hook, it just gets "hooked".

**Comment by wilzbach** [comment]
> Still trying to figure out why the GH status doesn't show.

... and since a couple of days (or more?) Travis seems to take quite a long time to start the build.
See also https://github.com/dlang/phobos/pull/4711#issuecomment-237692802

**Comment by wilzbach** [comment]
>>> I digged a bit and found this:
>> Travis-CI currently provides five concurrent builds for open source projects, and this is counted against all repositories per GitHub login or organization, as the Apache Software Foundation discovered. Travis counts each "build job", across all projects and pull requests, towards this limit on concurrent builds.
> Is DMD using up all builds?

It really seems like DMD is clogging the queue for druntime + phobos.

Currently running:

image

Still in the queue:

image

@MartinNowak any ideas on this problem? Should we use CircleCi (or another free CI) instead for the coverage testing at druntime and Phobos?

**Comment by wilzbach** [comment]
>  Should we use CircleCi (or another free CI) instead for the coverage testing at druntime and Phobos?

CircleCi  has four concurrent builds, here's a list of other providers

- [Wercker](http://wercker.com/pricing/) - 2 Concurrent builds
- [Drone.io](https://drone.io/) - I could only find "unlimited" builds
- [MagnumCI](https://magnum-ci.com/pricing) - 1 Concurrent build
- [Codeship](https://codeship.com/pricing) - 1 Concurrent build

For completion other known CIs that aren't suitable include:
- [SnapCI](https://snap-ci.com/my_plans/) - only one repository for free
- [Semaphore](https://semaphoreci.com/pricing) - non-free 
- [Buildkite](https://buildkite.com/pricing) - non-free

I think the basic idea is just to pick _any_ CI that is not Travis no avoid the clogged queue and waiting hours for feedback (note that it also increases the queue time for dmd).

**Comment by MartinNowak** [comment]
Let's rather stick w/ CircleCI for coverage then. Can we solve the problem that they don't use the merge commit, but just the HEAD of the souce branch, e.g. by manually merging into the target branch?

**Comment by MartinNowak** [comment]
> Let's rather stick w/ CircleCI for coverage then. Can we solve the problem that they don't use the merge commit, but just the HEAD of the souce branch, e.g. by manually merging into the target branch?

Maybe let me cleanup the circleci testing for dmd first, there are a couple of issues.

**Comment by wilzbach** [comment]
> Let's rather stick w/ CircleCI for coverage then. Can we solve the problem that they don't use the merge commit, but just the HEAD of the souce branch, e.g. by manually merging into the target branch?

I don't see any reason why this shouldn't work (if there is a merge conflict, it can't be merged anyways). btw isn't that what DAutoTest is doing too?
However there is one thing that could be problematic: I don't know yet how we know the target branch (see e.g. [this question](https://discuss.circleci.com/t/how-to-get-the-pull-request-upstream-branch/5496/2)).

**Comment by MartinNowak** [comment]
> However there is one thing that could be problematic: I don't know yet how we know the target branch (see e.g. this question).

Just working on that, I suspect we'll have to get the PR and ask github for that information.

**Comment by wilzbach** [comment]
> Just working on that, I suspect we'll have to get the PR and ask github for that information.

Yeah I thought so too, but was afraid that we might run into rate-limiting.
Btw you know that you can SSH into the [builds](https://circleci.com/docs/ssh-build/) at CircleCI? ;-)

**Pull request merged**
