### PR TITLE
[Musl] add to syslog.d

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Hm, do I need to do something more for this to land in an actual release? It appears this isn't in the lastest DMD yet so I need to mirror this change in my projects.

**Comment by thewilsonator** [comment]
It should be. 2.091 was released 8th march

**Comment by Cogitri** [comment]
A derp, I built DMD 2.091 but forgot to actually install it. Thanks for the message :)

**Comment by thewilsonator** [comment]
Haha. No problems.

**Pull request merged**
