### PR TITLE
Annotate `toThread` parameter `t` with `return scope`

### PR DESCRIPTION
**Pull request by nordlow**
Unblocks https://github.com/dlang/dmd/pull/12520, @thewilsonator

### CODE REVIEW

**Comment by thewilsonator** [comment]
need to target stable.

**Review by thewilsonator — APPROVED** [review]

**Comment by nordlow** [comment]
> need to target stable.

Done

**Comment by Geod24** [comment]
Need a rebase too.

**Comment by nordlow** [comment]
> Need a rebase too.

Done

**Comment by nordlow** [comment]
> > Need a rebase too.
> 
> Done

Hmm, the diff doesn't look right...

**Comment by nordlow** [comment]
> > > Need a rebase too.
> > 
> > 
> > Done
> 
> Hmm, the diff doesn't look right...

Rebase again.

**Pull request merged**
