### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by thewilsonator**
Fingers crossed

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
The deprecation are irrelevant. The compilations succeeds but running the executable fails.

**Comment by thewilsonator** [comment]
Oh, Maybe i was misread the `-w` as `-W`.

**Comment by MoonlightSentinel** [comment]
Unless there is an actuall issue with the `real` formatting which causes a crash in Mingw (the Azure job is the only one testing it IIRC)

**Comment by thewilsonator** [comment]
I thought the command line that was set to error on deprecations.

**Pull request closed without merging**
