### PR TITLE
Issue 22689: core.sys.posix.sys.dirent: Separate OS dirent struct from C runtime functions and flags

### PR DESCRIPTION
**Pull request by ibuclaw**
This struct is tied to the kernel, not the C run-time.

### CODE REVIEW

**Comment by CyberShadow** [comment]
> This struct is tied to the kernel, not the C run-time.

Is this accidental (the C runtimes simply expose/use the data structure used in the syscall) or is there some guarantee?

**Comment by ibuclaw** [comment]
> > This struct is tied to the kernel, not the C run-time.
> 
> Is this accidental (the C runtimes simply expose/use the data structure used in the syscall) or is there some guarantee?

These definitions are found in "bits" headers.  So they are not really part of the C API, just architecture/kernel-specific bindings in C.

**Comment by CyberShadow** [comment]
> These definitions are found in "bits" headers. So they are not really part of the C API, just architecture/kernel-specific bindings in C.

I thought the `bits` directory just meant "implementation bits that you shouldn't include directly". Does it have additional meaning (definitions that are not specific to the libc)? I'm not sure that would be accurate considering it also has files like `libc-header-start.h` (which seems very libc-specific) and `locale.h` (which seems to pertain an entirely userspace topic).

Best I could find: https://stackoverflow.com/questions/66848294/what-does-bits-directory-stand-for-in-glibc-project

**Comment by ibuclaw** [comment]
A platform is broken due to the blanket switch from `linux` to `CRuntime_Glibc`, and you choose to have this conversation now? :-)

Obviously my answer isn't one-size-fits-all, however I can't see there being any per-os-per-arch definitions outside of the sysdeps directory in the glibc source tree (bottom entry is generic)
```
./sysdeps/unix/bsd/bsd4.4/kfreebsd/bits/dirent.h
./sysdeps/unix/sysv/linux/alpha/bits/dirent.h
./sysdeps/unix/sysv/linux/bits/dirent.h
./bits/dirent.h
```

It's certainly not helped that the druntime modules smash both headers together and assume that because it's glibc, it must be the case for everyone.

**Comment by ibuclaw** [comment]
It also doesn't help that there is no separation between OS and runtime for other version flags, but it's really the exception rather than the rule that such combinations exist (apart from Linux, only FreeBSD, Solaris, and Windows have been ported to other C runtimes).

I have full confidence that these series of PRs are will break Cygwin where it previously silently might have compiled due to `CRuntime_Glibc` definitions being all their correct places.  This is a good thing, as Cygwin definitions should be treated as it's own "OS" distinct from Glibc when it comes round to porting it "proper".

**Comment by CyberShadow** [comment]
> A platform is broken due to the blanket switch from `linux` to `CRuntime_Glibc`, and you choose to have this conversation now? :-)

Hey, be nice. :)

- Code reviews are meant to be collaborative, not adversarial.
- I'm assuming that you're the expert on this topic here, so I've asked in genuine curiosity, not in trying to act as some gate keeper.
- Didn't know this was some urgent regression.
- Even if it is, is this the minimal change needed to fix it? Would it be better to make the minimal change now, and think about the best way to structure things across platforms later?

> It's certainly not helped that the druntime modules smash both `dirent.h` and `bits/dirent.h` headers together and assume that because it's glibc, it must be the case for everyone.

I don't understand why that's important. Are `dirent.h` and `bits/dirent.h` maintained by different parties in other libcs?

> It also doesn't help that there is no separation between OS and runtime for other version flags, but it's really the exception rather than the rule that such combinations exist (apart from Linux, only FreeBSD, Solaris, and Windows have been ported to other C runtimes) - however it does mean that annoyingly `CRuntime_Glibc` must come first in any chain of version conditions, as it is unknown whether i.e `OpenBSD` is referring to the C runtime or Kernel (whereas `CRuntime_OpenBSD` would be explicit in that).

So I guess it all goes back to us not following the file structure of each platform/libc's header files, and instead using `version` blocks; but, doing things this way still doesn't seem pedantically correct to me, as glibc could in theory definitely choose to use a different definition of `dirent` than the libc that the OS ships with.

In any case, thanks for the explanation :)

**Comment by ibuclaw** [comment]
> * Didn't know this was some urgent regression.

Bug reports in gdc, so trying to keep them down, and keeping things portable is a bit of a bug bear of mine.

>  * Even if it is, is this the minimal change needed to fix it?

It started off with an abort in `_d_dso_registry` that was tracked down to [RTLD flags passed to `dlopen` being FreeBSD's instead of Glibc's](https://github.com/dlang/druntime/pull/3678), then the GC threw an OutOfMemoryException whenever `new` was requested, and that was because [MAP flags passed to `mmap` being Glibc's instead of FreeBSD's](https://github.com/dlang/druntime/pull/3679) (in other words, the opposite).  Currently, the D compiler fails to open _any_ module, printing to the console: `read error: Success`. Why?  Because the version of `stat_t` imported is for Linux, not FreeBSD.

It's at this point I decided to have a quick look at how deep this rabbit hole really is:
```
glibc-2.33# ls ./sysdeps/unix/bsd/bsd4.4/kfreebsd/bits/
auxv.h	  ioctls.h	 os-unistd.h  sched.h	   signum.h  stat.h	    termios.h	 waitflags.h
dirent.h  ioctl-types.h  param.h      sem.h	   sigset.h  statvfs.h	    time.h	 waitstatus.h
errno.h   ipc.h		 poll.h       shm.h	   socket.h  sys_errlist.h  typesizes.h
fcntl.h   mman.h	 posix_opt.h  sigaction.h  stat16.h  syslog-path.h  uio.h
in.h	  msq.h		 resource.h   siginfo.h    statfs.h  sysmacros.h    utsname.h
```
Every header in there that has an equivalent in `core.sys.posix` means we have a bug on our hands when it comes to the use of `CRuntime_Glibc`.

>  Would it be better to make the minimal change now, and think about the best way to structure things across platforms later?

It's certainly a start, though I wouldn't call it minimal.  There's a lot of file to comb through to check whether `CRuntime_Glibc` is being using appropriately.  This is just putting a line down to ensure that `CRuntime_Glibc` is not always taken to mean `linux`.  There's plenty of other things that need to be tackled too for other ports, such as ensuring that `Solaris` is not taken to mean `X86`, because there's still a few outstanding failed tests that boil down to wrong bindings on the `SPARC` for Solaris.

> > It's certainly not helped that the druntime modules smash both `dirent.h` and `bits/dirent.h` headers together and assume that because it's glibc, it must be the case for everyone.
> 
> I don't understand why that's important. Are `dirent.h` and `bits/dirent.h` maintained by different parties in other libcs?
> 

Ah no, I meant that the vector for combinations of what bindings gets installed has another edge that wasn't considered when `linux` was switched over to `CRuntime_Glibc`.  At the moment in druntime we have `CRuntime_Glibc` at the top (i.e: `dirent.h` and others), then architecture-specific bindings nested within (i.e: what's found in `<arch>/bits/dirent.h`).  But actually there are variations of OS-specific bindings on top of the architecture-specific bindings too (i.e: `<os>/<arch>/bits/dirent.h`).

kFreeBSD is one example of this (however, maintained outside glibc in Debian), and kOpenSolaris is another (albeit a dead one).  One that does seem to be maintained in-tree though (and there's an active port in Debian too) is GNU/Hurd, which would also be `CRuntime_Glibc`, but with a different set of OS-specific flags and types to Linux.

Breaking things apart like this whilst needed in order to unbreak kFreeBSD, also paves the way to add Hurd at some point in the future too.

> > It also doesn't help that there is no separation between OS and runtime for other version flags, but it's really the exception rather than the rule that such combinations exist (apart from Linux, only FreeBSD, Solaris, and Windows have been ported to other C runtimes) - however it does mean that annoyingly `CRuntime_Glibc` must come first in any chain of version conditions, as it is unknown whether i.e `OpenBSD` is referring to the C runtime or Kernel (whereas `CRuntime_OpenBSD` would be explicit in that).
> 
> So I guess it all goes back to us not following the file structure of each platform/libc's header files, and instead using `version` blocks; but, doing things this way still doesn't seem pedantically correct to me, as glibc could in theory definitely choose to use a different definition of `dirent` than the libc that the OS ships with.
> 

It could, but wouldn't that be expensive to do so?  What I infer from the kFreeBSD C headers is that everything matches the FreeBSD kernel types and flags so that they don't have to convert/translate from Glibc-Linux types/flags internally before passing it over to whatever syscall each function ultimately results in.

**Review by CyberShadow — APPROVED** [review]

**Comment by CyberShadow** [comment]
Makes sense, thank you for the great explanation. Do you think we can continue down this path while maintaining the linear top-level `version`...`else` chain? Intuitively I would think that it would make sense to have a file for each kernel / native libc (for OSes which distribute their libc), and for glibc, make select structures aliases to those types. That would also allow room for us supporting a future hypothetical libc which has different rules for when it chooses to use the kernel's types.

**Comment by ibuclaw** [comment]
> Makes sense, thank you for the great explanation. Do you think we can continue down this path while maintaining the linear top-level `version`...`else` chain? Intuitively I would think that it would make sense to have a file for each kernel / native libc (for OSes which distribute their libc), and for glibc, make select structures aliases to those types. That would also allow room for us supporting a future hypothetical libc which has different rules for when it chooses to use the kernel's types.

I've tried splitting up bindings into per-platform or per-arch modules in the past (Walter even had a go at a simple module #744), and whilst it looks tidy for small things, for the bigger modules it becomes an absolute rats nest, and only increases burden for maintenance (i.e: #1255).

Maybe the approach I took 7 years ago was wrong though, and there's a more intuitive way to do it.

If there's going to be a support added for a new CRuntime to druntime in the mid-term, it's going to be `CRuntime_Newlib`. :-)

Ultimately, I'd rather these bindings be auto-generated from the target at build-time, or better yet importC and we delete all these bindings for good (just have to deal with the fallout of destroying the ad-hoc module layout) - but we are currently not there yet.

**Comment by ibuclaw** [comment]
For now, best thing to do is to [let sleeping dogs lie](https://www.phrases.org.uk/meanings/let-sleeping-dogs-lie.html) and keep what we have with the single module, large chain of version conditions.  Just keep nudging it in the direction this PR is going and make absolutely sure the version being used is the most appropriate one, and remember which versions are mutually exclusive, and which _can_ co-exist in an amalgamation platform.

**Pull request merged**
