### PR TITLE
Remove references to `extern(Pascal)`

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by Geod24** [comment]
You were faster than me. However, please don't create branch in the upstream repo, it becomes messy very quickly.

**Comment by thewilsonator** [comment]
Gah, I keep forgetting that it no longer defaults to my repo.

**Comment by Geod24** [comment]
@thewilsonator :

> Gah, I keep forgetting that it no longer defaults to my repo.

Next time you update your master (I guess that's where you branch from), do `git push reponame -u` ;)

**Comment by Geod24** [comment]
Walter approved the deprecation, can we move forward with this ?

**Comment by ZombineDev** [comment]
Here's the full list:
```
./benchmark/gcbench/vdparser.extra/vdc/parser/mod.d:630://    "Pascal"
./benchmark/gcbench/vdparser.extra/vdc/parser/mod.d:694:        case "Pascal":  return Attr_ExternPascal;
./benchmark/gcbench/vdparser.extra/vdc/util.d:113:    ExternPascal,
./benchmark/gcbench/vdparser.extra/vdc/util.d:127:enum Attr_CallMask   = Attr_ExternC | Attr_ExternCPP | Attr_ExternD | Attr_ExternWindows | Attr_ExternPascal | Attr_ExternSystem;
./benchmark/gcbench/vdparser.extra/vdc/util.d:222:        case Attr_ExternPascal:  return "extern(Pascal)";
./benchmark/gcbench/vdparser.extra/vdc/util.d:261:        case Attr_ExternPascal:  return "__pascal";
./src/core/sys/windows/winnetwk.d:298:extern (Pascal) {
./src/core/sys/windows/httpext.d:70:    extern(Pascal) BOOL function(HCONN, LPSTR, LPVOID, LPDWORD)
./src/core/sys/windows/httpext.d:72:    extern(Pascal) BOOL function(HCONN, LPVOID, LPDWORD, DWORD) WriteClient;
./src/core/sys/windows/httpext.d:73:    extern(Pascal) BOOL function(HCONN, LPVOID, LPDWORD) ReadClient;
./src/core/sys/windows/httpext.d:74:    extern(Pascal) BOOL function(HCONN, DWORD, LPVOID, LPDWORD, LPDWORD)
./src/core/sys/windows/httpext.d:79:extern (Pascal) {
./src/core/sys/windows/httpext.d:110:extern (Pascal) {
./src/core/sys/windows/mapi.d:127:extern (Pascal) {
./src/core/demangle.d:1011:        V       // Pascal
./src/core/demangle.d:1091:        case 'V': // Pascal
./src/core/demangle.d:1093:            put( "extern (Pascal) " );
./src/core/demangle.d:2382:    // C || Pascal || Windows
./src/core/demangle.d:2383:    enum hasPlainMangling = lnk == "C" || lnk == "Pascal" || lnk == "Windows";
./src/core/demangle.d:2390:    static extern(Pascal) void fooP();
./import/core/sys/windows/winnetwk.d:298:extern (Pascal) {
./import/core/sys/windows/httpext.d:70:    extern(Pascal) BOOL function(HCONN, LPSTR, LPVOID, LPDWORD)
./import/core/sys/windows/httpext.d:72:    extern(Pascal) BOOL function(HCONN, LPVOID, LPDWORD, DWORD) WriteClient;
./import/core/sys/windows/httpext.d:73:    extern(Pascal) BOOL function(HCONN, LPVOID, LPDWORD) ReadClient;
./import/core/sys/windows/httpext.d:74:    extern(Pascal) BOOL function(HCONN, DWORD, LPVOID, LPDWORD, LPDWORD)
./import/core/sys/windows/httpext.d:79:extern (Pascal) {
./import/core/sys/windows/httpext.d:110:extern (Pascal) {
./import/core/sys/windows/mapi.d:127:extern (Pascal) {
./import/core/demangle.d:1011:        V       // Pascal
./import/core/demangle.d:1091:        case 'V': // Pascal
./import/core/demangle.d:1093:            put( "extern (Pascal) " );
./import/core/demangle.d:2382:    // C || Pascal || Windows
./import/core/demangle.d:2383:    enum hasPlainMangling = lnk == "C" || lnk == "Pascal" || lnk == "Windows";
./import/core/demangle.d:2390:    static extern(Pascal) void fooP();
```

**Comment by thewilsonator** [comment]
`import` is a generated directory.
The windows functions have all since been updated from `Pascal` to `Windows`. 
I'd rather not change the visualD and other associated (de)mangling as this is only a deprecation not a removal.

This list in this diff is therefore complete.

**Comment by ZombineDev** [comment]
Yep, you're right.

**Comment by wilzbach** [comment]
Please remember to delete branches created at upstream or better create them at your fork.

**Pull request merged**
