### PR TITLE
Deprecated callStructDtorsDuringGC

### PR DESCRIPTION
**Pull request by JinShil**
Supersedes https://github.com/dlang/druntime/pull/2513

cc @rainers @edi33416 @andralex

### CODE REVIEW

**Comment by andralex** [comment]
I'm all for this. @atilaneves ?

**Comment by JinShil** [comment]
Now targeting stable

**Comment by thewilsonator** [comment]
I'm assuming that the build kite phobos failure is bogus given that the autotester passes.

**Comment by atilaneves** [comment]
I was going to say "fine by me as well" but it's already been merged anyway.

**Pull request merged**
