### PR TITLE
Revert "core.checkedint.addu: Faster (like subu: only one compare-and-branch)."

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/druntime#3496

Testing to see if this resolves https://github.com/dlang/dmd/pull/12823#issuecomment-875115091

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]
The OMF build passed!
Should obviously be resubmitted once the Optlink situation is resolved

**Comment by ibuclaw** [comment]
FYI @DoctorNoobingstoneIPresume.

**Comment by ibuclaw** [comment]
Thanks @MoonlightSentinel for tracking it down.

**Comment by WalterBright** [comment]
The triggering piece of code in the PR can be tracked down with a binary search.

**Comment by Geod24** [comment]
> The triggering piece of code in the PR can be tracked down with a binary search.

Yes but it's a distraction from the actual work the person was trying to do. Optlink has been a torn in our side since forever, as its errors are impossible to debug. When can we finally stop shipping it ?

**Comment by thewilsonator** [comment]
whenever we get around to dropping OMF completely, which shouldn't be too hard. We ship LLD, I'm not sure if we ship the VC redistributables.

**Comment by DoctorNoobingstoneIPresume** [comment]
> > The triggering piece of code in the PR can be tracked down with a binary search.
> 
> Yes but it's a distraction from the actual work the person was trying to do. Optlink has been a torn in our side since forever, as its errors are impossible to debug. When can we finally stop shipping it ?

I wish that optlink is kept forever. It is incredibly fast and it allows to run dmd on Windows XP. This should, of course, count !

More importantly: Having several builds of the toolchain allows us to find errors which simply do not manifest themselves by accident on one build.

@WalterBright Is it possible to build DMD (for OMF and 32-bit Windows) starting with just the freeware DMC, please ?

**Comment by thewilsonator** [comment]
> It is incredibly fast and it allows to run dmd on Windows XP.

It's incredibly buggy and XP has been EOL for how long?

> More importantly: Having several builds of the toolchain allows us to find errors which simply do not manifest themselves by accident on one build.

dropping it allows us to avoid all those errors completely.

**Comment by ibuclaw** [comment]
> > > The triggering piece of code in the PR can be tracked down with a binary search.
> > 
> > Yes but it's a distraction from the actual work the person was trying to do. Optlink has been a torn in our side since forever, as its errors are impossible to debug. When can we finally stop shipping it ?
> 
> I wish that optlink is kept forever. It is incredibly fast and it allows to run dmd on Windows XP. This should, of course, count !
> 

Surely not, XP uses COFF as its default format too. The only place where I've seen OMF as a hard requirement is on 16-bit Intel.

**Comment by DoctorNoobingstoneIPresume** [comment]
> > It is incredibly fast and it allows to run dmd on Windows XP.
> 
> It's incredibly buggy and XP has been EOL for how long?

I agree that this is a minority point of view. As a partial counter-argument, I wish to say that the differences between Windows XP and the last version of Windows 10 there should not be relevant for a command-line toolchain.

> > More importantly: Having several builds of the toolchain allows us to find errors which simply do not manifest themselves by accident on one build.
> 
> dropping it allows us to avoid all those errors completely.

I think we are talking about different errors...

**Comment by DoctorNoobingstoneIPresume** [comment]
> Surely not, XP uses COFF as its default format too. The only place where I've seen OMF as a hard requirement is on 16-bit Intel.

Microsoft's toolchains use COFF.

There are toolchains, even for Windows 10, which use OMF: Digital Mars and Embarcadero (for 32-bit) (even the clang-based version, I think).

**Pull request merged**
