### PR TITLE
Remove pointless version(unittest)

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by schveiguy** [comment]
There's another one a few more lines above.

**Comment by schveiguy** [comment]
FIFY :)

**Comment by schveiguy** [comment]
Why is circleci failing with that core.time test? Seems very odd.

**Comment by wilzbach** [comment]
Thanks! See https://github.com/dlang/druntime/pull/2048

**Comment by schveiguy** [comment]
> See #2048

Whew! I thought maybe the `version(unittest)` removal was causing it 😄 . Still very strange.

**Pull request merged**
