### PR TITLE
[stable] OpenBSD core.sys.posix.semaphore: sem_t should be a pointer to an opaque struct

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by Geod24** [comment]
Can you add a rationale for those of us not familiar with OpenBSD ?

**Comment by ibuclaw** [comment]
C doesn't allow empty structs so the declaration on our side is obviously wrong (even though it makes no difference).

**Comment by ibuclaw** [comment]
C doesn't allow empty structs so the declaration on our side is obviously wrong (even though it makes no difference).

**Review by ibuclaw — APPROVED** [review]

**Comment by n8sh** [comment]
>Can you add a rationale for those of us not familiar with OpenBSD ?

It is the definition in the C header file.

[OpenBSD semaphore.h](https://github.com/openbsd/src/blob/8ab20fcdaed7622dbbbf217b7d48250d1c04c156/include/semaphore.h#L42-L44)
```c
/* Opaque type definition. */
struct __sem;
typedef struct __sem *sem_t;
```

**Pull request merged**
