### PR TITLE
Revert "EASY: Move radix to template parameter in unsignedToTempString"

### PR DESCRIPTION
**Pull request by Geod24**
Reverts dlang/druntime#3167

It was force pushed while red and broke master. We should *never* do that.
See companion PR: https://github.com/dlang/phobos/pull/7567

### CODE REVIEW

**Comment by Geod24** [comment]
Force-pushed the Phobos revert, this should go green now.

**Comment by Geod24** [comment]
Azure fails at the checkout step:
```console
Generating script.
Script contents:
git clone --branch revert-3167-unsignedToTempString https://github.com/dlang/dmd.git ../dmd
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\1ea1e34b-99f0-426c-91f0-c9f3787a0065.cmd""
Cloning into '../dmd'...
fatal: Remote branch revert-3167-unsignedToTempString not found in upstream origin
##[error]Cmd.exe exited with code '128'.
```

Looks like a CI bug, where it gets confused because I clicked the "revert" button. @wilzbach do you know what might cause it ?

**Comment by andralex** [comment]
Wow that's quite some aggravation. Sorry folks. Should I force push this, or does it make it just worse?

**Comment by wilzbach** [comment]
There's some logic for most CIs to check-out matching branches like master or stable. It looks like the azure try to do the same, but fail.
Solutions:
- force-merge revert
- open revert from user account branch
- fix azure scripts to soft-fallback to master as default

**Comment by andralex** [comment]
OK I force merged...

**Pull request merged**
