### PR TITLE
core/threadasm.S: PPC64 fix undefined reference to core.thread.callWithStackShell

### PR DESCRIPTION
**Pull request by ibuclaw**
Looks like a copy-pasto from #988.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Ping @redstar

**Comment by ZombineDev** [comment]
As mentioned in https://github.com/dlang/druntime/pull/1933#issuecomment-336381942, I trust that @ibuclaw will follow through with another PR if needed.

**Comment by ibuclaw** [comment]
@ZombineDev linker fails without this patch, and it looks obviously wrong.

**Comment by redstar** [comment]
Yes, it is obviously wrong. In newer versions of LDC `callWithStackShell()` is implemented as inline assembler in `thread.d`.

**Pull request merged**
