### PR TITLE
Prepare for stack-allocated array literals passed to scope slice params

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by schveiguy** [comment]
Shouldn't templates be inferred for scope-ness?

**Comment by kinke** [comment]
I didn't want to dig into why it was necessary to overcome DIP1000 errors when making the testcase in the linked DMD PR `@safe`:
```
test\runnable\test20734.d(17): Error: reference to local variable __arrayliteral_on_stack3 assigned to non-scope parameter a calling core.internal.destruction.__ArrayDtor!(S).__ArrayDtor
```

**Comment by MoonlightSentinel** [comment]
Another case where DIP1000 doesn't like expression temporarys ...

**Comment by schveiguy** [comment]
OK yeah, template inference sometimes breaks down, I've seen it with other things. I wish dip1000 was easier to figure out.

**Comment by Geod24** [comment]
This fixed issue https://issues.dlang.org/show_bug.cgi?id=18872

**Pull request merged**
