### PR TITLE
core.memory.__delete: Fix order in which arrays of structs are destructed

### PR DESCRIPTION
**Pull request by JinShil**
This issue was discovered while working on https://github.com/dlang/dmd/pull/9666

This test https://github.com/dlang/dmd/blob/b0007c1193dfb72bcfa8cef3f420fee68564ce49/test/runnable/sdtor.d#L186-L208

does not pass when `delete` is replaced with `__delete`.  This PR fixes that.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please target stable.

Is there an issue number for this?

**Comment by JinShil** [comment]
> Is there an issue number for this?

I did not file an issue for it.

**Comment by thewilsonator** [comment]
It should probably have a line in the changelog, closing a bug will do that.

**Comment by JinShil** [comment]
Will submit a new PR.

**Pull request closed without merging**
