### PR TITLE
Fix Issue 19005 - [REG2.081-b1] object.hashOf no longer works for std.datetime.date.Date

### PR DESCRIPTION
**Pull request by n8sh**
Resubmission of #2223 to target stable, again.

### CODE REVIEW

**Comment by schveiguy** [comment]
I tested locally, the changes in #2226 fix the issue, so I think we should go that route.

**Comment by n8sh** [comment]
> I think we should go that route.

@schveiguy We need to go both routes. There are two bugs. The bug in `hash.d` is that `toUbyte` is called in a branch where we have determined that `toUbyte` cannot be called. The bug in `convert.d` is that `toUbyte` should be callable on enums but isn't.

**Comment by schveiguy** [comment]
OK, *now* I see what you are talking about. I didn't see the static if above (it was helpfully cut off by github when doing the review). However, let's take a step back...

PR #2226 is *also* fixing 19005 with `Date.hashOf`, because now it *can* call toUbyte on the enum, and the second branch isn't even used, the first one is. I've verified your test case here does pass with that change alone. So the unittest can go in either PR, we can just leave it here.

You are right that this second branch is nonsense. Looking at the history, I can see that what you are writing here re-implements what was there before, but I'm curious if it will ever be triggered with your enum fix. I wonder if it was a "I can't figure out why this is working, I'll just stick this here" branch. It seems rather odd to reproduce the `toUbyte` code locally.

Looks like the branch was originally in this when first committed. I wonder if the kinks have all been worked out in `toUbyte` that would make this work? Maybe the enum fix is what would do it?

BTW, can you fix the typo "unsupproreted" to "unsupported"?

**Comment by schveiguy** [comment]
OK, now I'm starting to understand this better. I didn't realize that the CTFE version must *still* compile, even if you only use the function at runtime. So that is why the repeat of the non-ctfe code is necessary.

I think this can be simplified. But probably not in the stable branch, I'll look into it once these are merged.

**Comment by n8sh** [comment]
>BTW, can you fix the typo "unsupproreted" to "unsupported"?

The comment seems to be outdated, so I'll just remove it.

**Pull request merged**
