### PR TITLE
[Trivial] core.thread: Fix missing alignment of global

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
Are pulls against `stable` discouraged these days? CI keeps having problems with it.

**Comment by wilzbach** [comment]
> Are pulls against stable discouraged these days? CI keeps having problems with it.

I fixed this yesterday: https://github.com/dlang/dlang.org/pull/1839

Sadly you need to rebase the PR, so that DAutoTest reruns. The trick is to do sth like this:

```
git commit --amend--no-edit
```

To get a new sha hash.

**Comment by kinke** [comment]
Thanks, done. Requires a new auto-merge OK though.

**Comment by wilzbach** [comment]
> Requires a new auto-merge OK though.

Done  :)

**Comment by wilzbach** [comment]
DAutoTest has been fixed in https://github.com/dlang/dlang.org/issues/1842
As this is a trivial change, it passes on all CIs and for some reason I can't force push here, I am manually overwriting this to avoid yet another ping-pong loop (this one-line PR has had much more activity than needed already).

**Pull request merged**
