### PR TITLE
ctfe-code is often annotated with pure @safe we want to print anyway

### PR DESCRIPTION
**Pull request by UplinkCoder**
As per title.
This signature change is needed to make the test work.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@klickverbot this is needed to get the test to run.
I forgot to add the attributes in the first PR.

**Comment by UplinkCoder** [comment]
It is a special debug tool. 
We will always special case.

**Comment by UplinkCoder** [comment]
I disagree with @safe.

**Comment by ZombineDev** [comment]
I agree with @klickverbot about `@safe`. Those functions don't do anything unsafe that needs to be trusted.

While we're at that, can we change the signature to `const(string)[]`? C.f. my rant about immutable in the [original PR](https://github.com/dlang/druntime/pull/1643#issuecomment-246271082).

**Comment by UplinkCoder** [comment]
@klickverbot it's @safe now.

**Comment by WalterBright** [comment]
Do we really need the "ln" variant?

**Comment by UplinkCoder** [comment]
@WalterBright not necessarily however since it only takes one string argument the ln variant takes quite some typing.

**Comment by UplinkCoder** [comment]
Furthermore the ln Variant was there before.
I don't see why we should remove it.

**Comment by UplinkCoder** [comment]
@klickverbot @WalterBright merge or close ?

**Comment by MartinNowak** [comment]
The signature can also be used w/ formattedWrite, formattedWrite((in char[] c) => __ctfeWrite(c.idup), "");.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
