### PR TITLE
Make Coverage checking more stable

### PR DESCRIPTION
**Pull request by wilzbach**
After @MartinNowak's nice work at https://github.com/dlang/dmd/pull/6022, here's a similar setup for Druntime.

Short summary
- Travis clogs our PR queue -> use CircleCi for coverage testing
- The coverage testing script now allows to run for 64-bit & 32-bit (a run takes only 3 minutes, so I think we can enable here two containers too)
- moved style check to the `posix.mak` as `style` target

### CODE REVIEW

**Comment by wilzbach** [comment]
> moved style check to the posix.mak as style target

Oh sorry ... `checkwhitespace` was already a defined target in the Makefile,  so I changed to `style` require it. `style` will be used for a similar PR at Phobos, s.t. we have clear naming and the style target at druntime could/should be expanded anyhow ;-)

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Can we also please enable CircleCI for druntime and Phobos @WalterBright @andralex.
https://circleci.com/add-projects

**Comment by andralex** [comment]
@MartinNowak are we good now?

**Comment by wilzbach** [comment]
> @MartinNowak are we good now?

Yep we are all set & all projects are enabled, only the configuration for Phobos in pending
See it in "live" e.g here:

https://github.com/dlang/druntime/pull/1602

**Pull request merged**
