### PR TITLE
Remove static initializer from struct `destroy`.

### PR DESCRIPTION
**Pull request by radcapricorn**
This change removes a shared static initializer from a `destroy`
implementation for structs, and with it a dependency on `memcpy`.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Hmm, this appears to have broken a few things:
```
ae 0.0.2292: building configuration "ae-test-library"...
--
  | /var/lib/buildkite-agent/builds/build2-1/dlang/druntime/build/distribution/bin/../imports/object.d(516,9): Error: cannot modify struct instance `*cast(Untyped*)&obj` of type `Untyped` because it contains `const` or `immutable` members
  | /var/lib/buildkite-agent/builds/build2-1/dlang/druntime/build/distribution/bin/../imports/std/typecons.d(6240,17): Error: template instance `object.destroy!(NamedPipeImpl)` error instantiating
```
Not sure if this is also related:
```
Generating test runner configuration 'sumtype-test-library' for 'library' (library).
--
  | Performing "unittest" build using dmd for x86_64.
  | sumtype 0.7.0: building configuration "sumtype-test-library"...
  | src/sumtype.d(855,8): Error: static assert:  "No matching handler for type `Evil`"
  | src/sumtype.d(693,14):        instantiated from here: `matchImpl!(SumType!(Evil, int))`
  | src/sumtype.d(280,9):        instantiated from here: `match!(SumType!(Evil, int))`
  | src/sumtype.d(560,2):        instantiated from here: `SumType!(Evil, int)`
```

**Comment by thewilsonator** [comment]
Perhaps just create a temporary on the stack and bitblast it and let the optimiser do its job?

**Comment by radcapricorn** [comment]
Ouch, that first one's bad. Could squash that with an `Unqual`, I guess. I really want a `memcpy` to **not** be there. Input welcome.
Not sure about the second one either, I'll take a look into SumType later, unless @pbackus could relate.

**Comment by thewilsonator** [comment]
I'm not sure `Unqual` would help because `struct Foo { immutable int i; }` is not going to change unless you manually strip out the immutable be reconstruction from the `.tupleof` which seems like overkill. 

You're going to end up with a `memcpy` there anyway because assignment of `.init` is going to copy from where `T.init` lives in the executable anyway.

**Comment by radcapricorn** [comment]
Letting the optimizer do the job is exactly why an explicit `memcpy` should not be there. Whether it ends up inserting a `memcpy` or just blasting values directly in there should be up to the compiler. Let's see how the updated version fares on those tests.

**Comment by thewilsonator** [comment]
Thats some nice wizardry!

**Comment by thewilsonator** [comment]
Appears to have fixed 'em both.

**Comment by radcapricorn** [comment]
:tada:

**Pull request merged**
