### PR TITLE
replace Error with assert in object.d

### PR DESCRIPTION
**Pull request by RazvanN7**
Revives: #2792

### CODE REVIEW

**Review by MartinNowak — APPROVED** [review]
Makes sense, will abort in production, and avoids exceptions for unreachable code.

**Comment by MartinNowak** [comment]
Looks like dmd's runnable/opover2.d test fails.

**Comment by ljmf00** [comment]
> Looks like dmd's runnable/opover2.d test fails.

I think this should be tested in `druntime` unittests instead of runnable compiler tests which is more appropriate by avoiding interdependencies with runtime library and way faster to test.

**Comment by RazvanN7** [comment]
It seems that the tests in `opover2.d` fail with "Illegal instruction". I don't understand why. It seems that when object.xopEquals is called and asserts, sometimes gets tripped off. On the other hand, the pattern used in `opover2.d` is throwing and catching an Error to test that the called methods are not implemented. All that code seems fishy.

**Comment by MoonlightSentinel** [comment]
> It seems that the tests in `opover2.d` fail with "Illegal instruction". I don't understand why. It seems that when object.xopEquals is called and asserts, sometimes gets tripped off. 

Druntime is compiled with `-release`, so `assert(0` is replaced with `ud` or similar.

> On the other hand, the pattern used in `opover2.d` is throwing and catching an Error to test that the called methods are not implemented. All that code seems fishy.

Indeed, tests for druntime should be moved to druntime.

**Comment by kinke** [comment]
> Makes sense, will abort in production, and avoids exceptions for unreachable code.

As DMD doesn't ship with debug druntime, it's not just for production, but the default behavior. Now if not even Razvan can make immediate sense of an SIGILL, imagine casual D users. So definitely no improvement in my eyes.

**Pull request closed without merging**
