### PR TITLE
Fix Issue 22219 - core.lifetime emplace is unsafe with void[] override

### PR DESCRIPTION
**Pull request by iK4tsu**

### CODE REVIEW

**Comment by aG0aep6G** [comment]
The following code must fail compilation, but this PR would allow it:

```d
import core.lifetime;
void main() @safe
{
    int*[1] p;
    void[] buf = p[];
    auto i = emplace!int(buf, 0xDEADBEEF); /* invalidates p[0] */
}
```

**Comment by iK4tsu** [comment]
Yeah, didn't think of that. This is a pretty hard edge case to cover. I'm not even sure if it can be covered. Any ideas?

**Comment by iK4tsu** [comment]
Maybe, instead of fixing this function, which takes a dynamic slice, I could implement another version that receives a static initialized void array:
```d
T* foo(T, size_t size)(return ref void[size] buf)
	if (size >= T.sizeof)
{
    return emplace!T(buf[0 .. size]);
}

void main()
{
    int*[1] p;
    void[p.sizeof] buf = p;
    assert(p.ptr !is buf.ptr);

	static assert (!__traits(compiles, { cast(void) foo!int(p); }));

    auto i = foo!int(buf);
    assert(*i == int.init);
    assert(p == [null]);
}
```

**Comment by aG0aep6G** [comment]
> Maybe, instead of fixing this function, which takes a dynamic slice, I could implement another version that receives a static initialized void array:
> 
> ```d
> T* foo(T, size_t size)(return ref void[size] buf)
> 	if (size >= T.sizeof)
> {
>     return emplace!T(buf[0 .. size]);
> }
> ```

I'm afraid that doesn't help. A `ref void[size]` can refer to the same memory as a `void[]`:

```d
void main()
{
    int*[1] p;
    void[] slice = p[];
    auto i = foo!int(slice[0 .. int.sizeof]);
    *i = 0xDEADBEEF; /* invalidates p[0] */
}
```

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
I don't think that the non-class override can be @safe. Since you are receiving a `void[]`, the parameter could have been initialized to point to anything. Without compiler dataflow analysis it it impossible to know, so I guess this is going to stay as it is.

The class overload is also introducing a regression. Below the modified test to be @safe ():

```d
void main() @safe
{
    static class C
    {
        int i;
        this(int i) @system {this.i = i; assert(0); }   // this constructor is called from @safe code
    }
    auto buf = new void[__traits(classInstanceSize, C)];
    auto c = emplace!C(buf, 5);
    assert(c.i == 5);
}
```

This code should be rejected as it calls a @system method.

**Comment by iK4tsu** [comment]
> I don't think that the non-class override can be @safe. Since you are receiving a `void[]`, the parameter could have been initialized to point to anything. Without compiler dataflow analysis it it impossible to know, so I guess this is going to stay as it is.
> 
> The class overload is also introducing a regression. Below the modified test to be @safe ():
> 
> ```d
> void main() @safe
> {
>     static class C
>     {
>         int i;
>         this(int i) @system {this.i = i; assert(0); }   // this constructor is called from @safe code
>     }
>     auto buf = new void[__traits(classInstanceSize, C)];
>     auto c = emplace!C(buf, 5);
>     assert(c.i == 5);
> }
> ```
> 
> This code should be rejected as it calls a @System method.

This actually does not compile under @safe code. The emplacement happens after the `void[]` is casted and if the `ctor` is @system then emplace is @system as well.

**Comment by RazvanN7** [comment]
> Regarding the class overload, is there any edge case I'm not seeing as well that could break this?

Nope, sorry. That was a mistake on my end.

I suggest we merge the class overload fix and abandon the non-class overload.

**Comment by aG0aep6G** [comment]
> I suggest we merge the class overload fix and abandon the non-class overload.

Maybe I'm missing something, but doesn't the class overload have the same issue I pointed out for the non-class one?

```d
import core.lifetime;
class C
{
    int x;
    this(int x) @safe { this.x = x; }
}
void main() @safe
{
    int*[100] p;
    void[] buf = p[];
    auto i = emplace!C(buf, 0xDEADBEEF); /* invalidates p */
}
```

**Comment by iK4tsu** [comment]
It seems it is. I guess I should close this PR altogether and invalidate the issue report.

**Pull request closed without merging**
