### PR TITLE
utf.d: use safe construct for .ptr instead

### PR DESCRIPTION
**Pull request by WalterBright**
Blocking https://github.com/dlang/dmd/pull/5860

### CODE REVIEW

**Comment by andralex** [comment]
noice

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Hm... since we *know* that r has a 0 termination, we know that r[0] is valid.

Seems like a wasteful bounds check. But of course, this can be a further enhancement, needs a `@trusted` escape.

ugh, and then there's the `r.length = s.length + 1` followed by `r.length = 0`. Which does nothing except throw away an allocation :)

**Comment by WalterBright** [comment]
> ugh, and then there's the r.length = s.length + 1 followed by r.length = 0. Which does nothing except throw away an allocation :)

It's meant to reserve the space, not throw away the allocation.

**Comment by aG0aep6G** [comment]
> It's meant to reserve the space, not throw away the allocation.

Would need assumeSafeAppend to make that work.

**Pull request merged**
