### PR TITLE
Fix Issue 11294 - Object destruction with alias this

### PR DESCRIPTION
**Pull request by radcapricorn**

### CODE REVIEW

**Comment by thewilsonator** [comment]
cc @RazvanN7 whats your take on this? Should this be fixed in the compiler rather than the runtime?

**Comment by Geod24** [comment]
I'd say compiler, but in the meantime, having a no-cost/trivial workaround in the runtime can't harm.

**Comment by RazvanN7** [comment]
The bug is another manifestation of : https://issues.dlang.org/show_bug.cgi?id=6777 . This should definitely be fixed in the compiler.

**Comment by thewilsonator** [comment]
@Geod24 that seems reasonable. @RazvanN7 how long do you think a fix will take?

**Comment by radcapricorn** [comment]
Maybe still add it until Issue 6777 is fixed, but add a `@@@BUG@@@` comment?

**Comment by thewilsonator** [comment]
Sounds good!

**Comment by RazvanN7** [comment]
> @RazvanN7 how long do you think a fix will take?
 
I will submit a patch today.

**Comment by thewilsonator** [comment]
Even better! Thanks!

**Comment by radcapricorn** [comment]
Oh, ok, will wait and test then.

**Comment by RazvanN7** [comment]
I've posted my patch for 6777 : https://github.com/dlang/dmd/pull/8712 .

Unfortunately, that patch alone does not suffice to fix this issue. There is another problem in the semantic of the cast expression, which I already have a solution for, but it needs the fix for 6777 to work.

**Comment by RazvanN7** [comment]
> So, if I understand correctly, the course of action now is to first get that fix in, then finish it off, and then this PR wouldn't be needed?

That is correct.

> Or shall I still leave it, to be reverted later?

This PR should stay open for the moment, because I am not sure if my PR is going to get in. I am confident that it will, but you never know if Walter might have some objections. Once Issue 11294 is completely fixed in dmd, we can close this PR

**Comment by radcapricorn** [comment]
Alright, thank you.

**Comment by RazvanN7** [comment]
I was thinking the same thing.

**Comment by Geod24** [comment]
The unittest makes sense, but the workaround is not necessary anymore.

**Comment by radcapricorn** [comment]
Maybe revert, then I'll remove the workaround but leave the unittest?

**Comment by Geod24** [comment]
> Maybe revert, then I'll remove the workaround but leave the unittest?

`git checkout -p 3b9c093d^ -- src/object.d` is enough.
https://github.com/dlang/druntime/pull/2378

**Pull request merged**
