### PR TITLE
Fix DDOC comments in core/stdc/errno.d

### PR DESCRIPTION
**Pull request by MoonlightSentinel**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
I used regex search+replace so there should be no issues here

**Comment by schveiguy** [comment]
I'd like to merge this, but the circleci build seems to have a spurious failure.

**Comment by Geod24** [comment]
@schveiguy : Retriggered the CI for you. You *should* be able to do it from CircleCI interface though.

**Comment by schveiguy** [comment]
I looked, but even though it said I was logged in, it didn't give me options to retry.

**Pull request merged**
