### PR TITLE
Add @nogc to pthread functions.

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes Issue 14601

### CODE REVIEW

**Comment by MartinNowak** [comment]
You need to move the function pointer types above the `@nogc:` declaration.
The way we did it in other modules was to create overloads for both `@nogc` and normal function pointer, then deprecated the normal ones.

**Comment by tmccombs** [comment]
Could you give me an example of a module where this was done?

**Comment by MartinNowak** [comment]
> Could you give me an example of a module where this was done?

It took me a while to remember which it was, core.sys.posix.signal.
Here is the [declaration for the signal handler  functions](https://github.com/dlang/druntime/blob/cf7a816dccd84e9a1353748c70357b03ea09b3cf/src/core/sys/posix/signal.d#L94-L101) and an [example for an overload](https://github.com/dlang/druntime/blob/cf7a816dccd84e9a1353748c70357b03ea09b3cf/src/core/sys/posix/signal.d#L1418-L1424).
If the type is part of the public API,

**Comment by tmccombs** [comment]
Thank you

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
