### PR TITLE
Don't assert on what name the binary is

### PR DESCRIPTION
**Pull request by ibuclaw**
Don't care what the binary name is, just get the dirname and do the right thing.

### CODE REVIEW

**Comment by ibuclaw** [comment]
The dejagnu testsuite that I run this under for gdc adds a `.exe` suffix to the binary name.

**Comment by nemanja-boric-sociomantic** [comment]
Perhaps just reword the commit, to make the intention for this clear (like in  your last comment)?

**Comment by Burgos** [comment]
Perhaps just reword the commit, to make the intention for this clear (like in your last comment)?

**Comment by ibuclaw** [comment]
@Burgos sure yeah.

**Comment by atilaneves** [comment]
LGTM

**Pull request merged**
