### PR TITLE
Sync Azure CI script with DMD's

### PR DESCRIPTION
**Pull request by kinke**
For consistent job names etc.

### CODE REVIEW

**Comment by kinke** [comment]
@Geod24: This could use the same umbrella branch requirement for Azure. And most likely needs a manual merge due to the Phobos regression on Win64.

**Comment by Geod24** [comment]
> And most likely needs a manual merge due to the Phobos regression on Win64.

All green here, which regression are we talking about ? Did the same modifications here w.r.t. job names.

**Comment by kinke** [comment]
The regression for DMD master wrt. x64 job with LDC as host compiler. - As it works fine with the DMD-host job, I strongly suspect the libcurl.dll copied from the host compiler for the Phobos unittests, which was updated with LDC v1.21 (used version is 1.20)...

**Comment by kinke** [comment]
@Geod24: This one'e still missing in the Azure series.

**Comment by kinke** [comment]
Ping.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
> @Geod24: This one'e still missing in the Azure series.

Just checked, settings seems correct. Perhaps the UI didn't refresh ?

**Comment by kinke** [comment]
[I meant the PR wasn't merged yet, while the others in the other repos were.]

**Pull request merged**
