### PR TITLE
Fix Issue 15322 - Correct versioning PENUM_PAGE_FILE_CALLBACK

### PR DESCRIPTION
**Pull request by LimiQS**
Correct versioning PENUM_PAGE_FILE_CALLBACK

### CODE REVIEW

**Comment by LimiQS** [comment]
> OK, but why remove the `PENUM_PAGE_FILE_CALLBACK` alias?

Sorry I missed that. Has been fixed.

**Comment by CyberShadow** [comment]
Nit, commit messages ought to be wrapped to 80 characters, and are in plain text (not Markdown).

**Comment by LimiQS** [comment]
> Nit, commit messages ought to be wrapped to 80 characters, and are in plain text (not Markdown).

Ok, I will follow this standard.

**Comment by kubo39** [comment]
Why not stable?

**Comment by thewilsonator** [comment]
@LimiQS your repository seems to have gone missing?

**Comment by kubo39** [comment]
@thewilsonator https://github.com/LimiQS/druntime/tree/patch-1 perhaps already restored, needs re-running auto-tester?

**Comment by thewilsonator** [comment]
Well Github says "Unknown repository".

**Comment by kubo39** [comment]
Hmm, ues, GitHub points to https://github.com/dlang/druntime/tree/patch-1, maybe GitHub's bug...?

**Comment by LimiQS** [comment]
It was missing, I restored branch manually.

**Pull request merged**
