### PR TITLE
Use `backtrace` on POSIX when available

### PR DESCRIPTION
**Pull request by Geod24**
Couple of low hanging fruit I caught while trying to debug the debug infos on OSX.

### CODE REVIEW

**Comment by Geod24** [comment]
Interesting. This changes the line information on one of the test, to be the line after the `throw`.
But it works correctly on Mac OSX... So I'll just version it for now.

**Comment by thewilsonator** [comment]
Whats the status of this?

**Comment by Geod24** [comment]
I was puzzled for a very long time as to why this changed the debug info. That might be due to another bug I found, and on which I worked last month (https://github.com/dlang/dmd/pull/10722#issue-362055337) but I'm not 100% positive.
No ETA as to when I'll come back to this yet. I will maybe separate some of the refactoring.

**Comment by thewilsonator** [comment]
OK, just clearing out some old GH notifications.

**Comment by yazd** [comment]
The reason for the difference is most likely due to the fact that `backtrace` returns the *return* addresses, however, for the stack trace, we'll need the *caller* addresses.

The code here https://github.com/dlang/druntime/blob/ef788b3be2b1074787668dd45f29ae20e38a335b/src/core/runtime.d#L768-L771 subtracts "CALL_INSTRUCTION_SIZE" to point to the *caller* address instead.

You can try doing the same with the output from `backtrace`.

**Pull request merged**
