### PR TITLE
compile posix errno_c.c file with ImportC

### PR DESCRIPTION
**Pull request by WalterBright**
After this succeeds, we'll do the other .c files in posix.mak.

### CODE REVIEW

**Comment by WalterBright** [comment]
It's definitely hanging compiling druntime/src/core/stdc/errno.c.

https://issues.dlang.org/show_bug.cgi?id=23207

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/14241

**Comment by thewilsonator** [comment]
Dependant PR merged.

**Comment by WalterBright** [comment]
buildkite druntime fails to build with:
```
~> make -f posix.mak -j2 buildkite-test
--
  | ../dmd/generated/linux/release/64/dmd -c -conf= -Isrc -Iimport -w -de -preview=dip1000 -preview=fieldwise -m64 -fPIC  -preview=dtorfields -O -release -inline  -version=Shared -fPIC -version=Shared -fPIC -I. -v src/core/stdc/errno.c -ofgenerated/linux/release/64/errno_c.o
  | make: ../dmd/generated/linux/release/64/dmd: Command not found
  | posix.mak:358: recipe for target 'generated/linux/release/64/errno_c.o' failed
  | make: *** [generated/linux/release/64/errno_c.o] Error 127
```
which means something is wrong with the buildkite setup, because `posix.mak` is using `$(DMD)` to run dmd.

**Comment by WalterBright** [comment]
Fixed the problem.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
