### PR TITLE
Add base address offset for PIE executables

### PR DESCRIPTION
**Pull request by yshui**
Fix the file name and line number in backtrace for PIE executables

### CODE REVIEW

**Comment by JinShil** [comment]
Is this a fix for https://issues.dlang.org/show_bug.cgi?id=18068?

Also, see https://github.com/dlang/druntime/pull/2172

**Comment by yshui** [comment]
@JinShil Oh no! I'm duplicating someone else's work again.

**Comment by JinShil** [comment]
@yshi, #2172  Well, given how that PR isn't going anywhere at the moment, feel fee to adopt it, or submit a competing PR.  We need that bug fixed.  cc @wilzbach

**Comment by yshui** [comment]
@JinShil What is needed to be done for #2172 ?

**Comment by JinShil** [comment]
> What is needed to be done for #2172 >

I'm not quite sure.  You'll have to read through the comments and see if you can obtain any information about it.  @wilzbach, being the author, may be able to provide you with more information.

**Pull request closed without merging**
