### PR TITLE
Change aliases to new syntax in several files

### PR DESCRIPTION
**Pull request by JackStouffer**
Modernization and clarity.

### CODE REVIEW

**Comment by joakim-noah** [comment]
FYI, #1002.

**Comment by JackStouffer** [comment]
Martin seems to be in favor of the new syntax.

The area I disagree with him on is the idea that people will just incrementally change the code to the new syntax. Sorry to be a cynic but if it hasn't happened after two years of pull requests it isn't going to happen.

**Comment by ZombineDev** [comment]
> Sorry to be a cynic but if it hasn't happened after two years of pull requests it isn't going to happen.

https://github.com/dlang/druntime/commit/d7581e817b37ccc0f4a502704ddcdb375a3b095a#diff-955ac66e3ac3a2edbe727ac0cf9fba4dR72 :P

Though I agree that it's better to do it once and be done with it.

**Comment by JackStouffer** [comment]
Ping @wilzbach. Do you think you could merge this?

**Comment by CyberShadow** [comment]
What's happening with this useless coverage thing, argh

**Comment by wilzbach** [comment]
> Ping @wilzbach. Do you think you could merge this?

Sorry - totally slipped through my radar. Rebased & auto-merging now, finally :)

**Pull request merged**
