### PR TITLE
pure functions infer scope, but not return 4

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by Geod24** [comment]
How many more of those are there ? It's pretty hard to understand what's the end goal from this PR.
This code obviously compile at the moment, but won't with a future change, I suppose. Could you link the change when making a PR ? And/or perhaps prior changes.

When searching the `git` history and trying to understand why a change was made, finding those PRs without explanation, comment, or link is really annoying because of how much time it makes you loose. Just having "fix things" or an issue number is pretty useless when using history or blame.

**Comment by WalterBright** [comment]
I have no idea how many more there are. In any case, the annotations are correct so I don't see it as really a problem.

**Comment by WalterBright** [comment]
The buildkite errors are irrelevant to this PR.

**Comment by aG0aep6G** [comment]
> This code obviously compile at the moment, but won't with a future change, I suppose. Could you link the change when making a PR ? And/or perhaps prior changes.

Since Walter apparently skimmed over that question: I believe these changes are in preparation for <https://github.com/dlang/dmd/pull/10924>.

**Comment by Geod24** [comment]
Thanks, that makes sense. I'll make this link more obvious in the other PRs.

**Pull request merged**
