### PR TITLE
core.checkedint.addu: Faster (like subu: only one compare-and-branch) (resubmit).

### PR DESCRIPTION
**Pull request by DoctorNoobingstoneIPresume**
https://github.com/dlang/druntime/pull/3511#issuecomment-875154147 ...

### CODE REVIEW

**Review by ibuclaw — DISMISSED** [review]
At this point, I'm not sure the druntime pipelines can be trusted.

**Comment by DoctorNoobingstoneIPresume** [comment]
> At this point, I'm not sure the druntime pipelines can be trusted.

"So I have heard.", @DoctorNoobingstoneIPresume typed with a hypocrite smile from his [Windows XP](https://github.com/dlang/druntime/pull/3511#issuecomment-875280738) computer.  :'(

**Review by DoctorNoobingstoneIPresume — COMMENTED** [review]
But it appears to me that these lines of code are actually covered by `unittest`s.

**Comment by RazvanN7** [comment]
@ibuclaw Any second thoughts on this?

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw Should this be closed or can we merge it?

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
