### PR TITLE
Deprecate callStructDtorsDuringGC

### PR DESCRIPTION
**Pull request by edi33416**
Please see #2509 for related discussion.

### CODE REVIEW

**Comment by wilzbach** [comment]
Changlog entry...

**Comment by rainers** [comment]
It doesn't help to print the deprecation when compiling druntime, it must be printed when the option is used, i.e. here: https://github.com/dlang/druntime/pull/2513/files#diff-50840eb79e3292d148af41006e3af980R51

**Comment by andralex** [comment]
I think this message will be printed while druntime is built, i.e. it is not client-visible at all. Its helpfulness is limited.

A better way to go about this is to detect the situation when user code is attempting to set that variable to `false`, and emit a deprecation message at that time (i.e. at run time).

**Comment by andralex** [comment]
@rainers saw yours after I typed in mine...

**Comment by JinShil** [comment]
> Message still printed at the wrong time (when compiling druntime rather than when it is used).

But how does one print a deprecation warning at runtime?  `fprintf(stderr, ...)`?

**Comment by rainers** [comment]
> `fprintf(stderr, ...)`?

Yes.

**Comment by JinShil** [comment]
https://github.com/dlang/druntime/pull/2743 was merged so I believe this can now be closed.

**Comment by thewilsonator** [comment]
Please reopen if this is still required.

**Pull request closed without merging**
