### PR TITLE
Updated makefile to use generated/os/release/model/dmd

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by wilzbach** [comment]
> Does this handle multilib builds, i.e. the building 32 bit libraries on a 64 bit system part?

Yes, `$(MODEL)` is set based on the system whereas `$(MODEL_FLAG)` (by default set to `$(MODEL)`) is used for building the libraries.

This is part of the [`osmodel.mak`](https://github.com/dlang/druntime/blob/master/osmodel.mak#L35)

**Comment by andralex** [comment]
Unclear on what the autotester issue is, but it looks like a one-off.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
@RazvanN7 please push again your repo so it kicks off the autotester

**Comment by andralex** [comment]
I'll take a risk to actually merge this

**Pull request merged**
