### PR TITLE
fix Issue 22843 - Program hangs on full gc collect with --DRT-gcopt=f…

### PR DESCRIPTION
**Pull request by huglovefan**
…ork:1 if run under valgrind/callgrind

the clone() call was using the `CLONE_CHILD_CLEARTID` flag without passing
 it a thread id pointer in the optional argument

based on the comment `// child thread id not needed`, the flag was probably
 intended to disable any passing of a thread id which is already the
 default if neither of `CLONE_CHILD_CLEARTID` and `CLONE_CHILD_SETTID` are
 used, so just remove the flag

### CODE REVIEW

**Comment by thewilsonator** [comment]
Thanks.

It should be possible to add the test case fo this issue as a shell test.
see https://github.com/dlang/druntime/blob/master/test/gc/Makefile#L52-L54 for setting the d runtime options.
You probably want to restrict the test to only run on linux (e.g. I don't have val grind installed on my Mac).

**Comment by huglovefan** [comment]
it has a test now

do the CI bots have valgrind installed to test this with / is there somewhere i should add it?

**Comment by thewilsonator** [comment]
> do the CI bots have valgrind installed to test this with / is there somewhere i should add it?

If any of them do it, it will be the linux boxes. If they don't fell free to do so.

Try adding to this file: https://github.com/dlang/druntime/blob/master/.cirrus.yml in the install script.

**Comment by huglovefan** [comment]
is it known what linux distro and version the D auto-tester has? i would like to replicate the segfault on it

**Comment by MoonlightSentinel** [comment]
`uname` reports `Linux redmond 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Review by rainers — APPROVED** [review]
LGTM.

I probably misread what this flag does und blindly copied it from elsewhere.

**Comment by huglovefan** [comment]
auto-tester's version of valgrind is too old and doesn't handle clone() correctly, the test now skips it

with this test program:

```D
import core.stdc.stdio;
import core.stdc.stdlib;
import core.sys.posix.signal;
import core.sys.linux.sched;
void main()
{
	extern(C) static int childfn(void*)
	{
		printf("in child\n");
		return 0;
	}
	ubyte[128000] stk;
	int pid = clone(&childfn, stk.ptr + stk.length, SIGCHLD, null);
	printf("pid = %d\n", pid);
}
```

it prints a weird result with the child also returning from clone()

```
human@ubuntu:~$ ./test
pid = 4062
in child
human@ubuntu:~$ valgrind --quiet --tool=none ./test
pid = 4064
pid = 4409364
==4064== 
==4064== Process terminating with default action of signal 11 (SIGSEGV)
==4064==  Access not within mapped region at address 0x0
==4064==    at 0x434826: _Dmain (in /home/human/test)
```

affects valgrind versions before 3.13.0 - auto-tester has 3.11.0 and cirrus CI 3.13.0

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Thanks for getting the test working.

**Pull request merged**
