### PR TITLE
Revert "Fix Issue 22552 - moveEmplace wipes context pointer of nested struct …"

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Reverts dlang/druntime#3638

---

This triggered the OMF pipelines to hang consistently due to yet another OPTLINK bug:

opt

### CODE REVIEW

**Comment by RazvanN7** [comment]
cc @radcapricorn

**Comment by radcapricorn** [comment]
Fiddlesticks! :\

**Comment by MoonlightSentinel** [comment]
> Fiddlesticks! :\

Indeed. But this revert should only be temporary until the OPTLINK issue is resolved

**Review by RazvanN7 — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Closing in favour of #3667

**Comment by ljmf00** [comment]
Just to be in sync, this is an upstream issue?

**Comment by MoonlightSentinel** [comment]
The failure is caused by OPTLINK, not Azure.

**Comment by ljmf00** [comment]
> The failure is caused by OPTLINK, not Azure.

Ah, I searched for optlink and didn't know that it was from Digital Mars. Got it.

**Comment by WalterBright** [comment]
Since this is an issue with the unittests, the thing to do here is to do a binary bisect on the unittests until the trigger is found.

**Comment by WalterBright** [comment]
Apparently no bugzilla issues was filed, either.

**Comment by MoonlightSentinel** [comment]
> Since this is an issue with the unittests, the thing to do here is to do a binary bisect on the unittests until the trigger is found.

OPTLINK segfaulted, the test passed for `-m32mscoff` (and all other platforms).
Feel free to fix OPTLINkbut that should not interfere with work done on druntime.

**Pull request closed without merging**
