### PR TITLE
Add pthread/math libraries to a couple more rules

### PR DESCRIPTION
**Pull request by marler8997**

### CODE REVIEW

**Comment by marler8997** [comment]
A good goal, but we're likely still a ways away from that. Once we can remove the make files in dmd, then I think we can start looking into that for druntime/photos.

In any case, this isn't improving the makefile, it is fixing a rule in the makefile and this fix will also be needed once we move to D.

**Comment by jacob-carlborg** [comment]
I thought bug fixes were improvements 😉

**Comment by marler8997** [comment]
True. Would have been better to say it's not an improvement specific for the makefile.

Hopefully dmd can drop the makefiles sooner rather than later. I've been pushing fixes to build.d to get it ready.

**Comment by jacob-carlborg** [comment]
They way to get someone to move to a new tool/system/whatever is to stop updating the old system and only update the new. Then eventually there will be enough features or bug fixes that exist in the new system and not the old that the user moves to the new system.

In this case this would mean not updating the makefiles and only update the D files. Even if the same bug exists in both.

**Comment by marler8997** [comment]
ready to merge?

**Pull request merged**
