### PR TITLE
Revert "linux: add system call bindings"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/druntime#2820

Broke _**every**_ supported Linux platform.

Don't merge _**ANY**_ new Linux bindings unless it supports all of the following:
- ARM
- AArch64
- HPPA
- HPPA64
- PPC
- PPC64
- MIPS
- MIPS64
- RISCV32
- RISCV64
- S390
- SystemZ
- SPARC
- SPARC64
- X86
- X86_64

Regular testing is done on these platforms and downstream testers **_do_** complain when you break the build for them.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by ljmf00** [comment]
> Regular testing is done on these platforms and downstream testers **_do_** complain when you break the build for them.

Is it possible to upstream some tests?

**Comment by jacob-carlborg** [comment]
> Is it possible to upstream some tests?

It's easy to run tests through emulation using Docker and QEMU: `docker run --platform "linux/$ARCH"`.

**Comment by ibuclaw** [comment]
@kinke might be better placed as ldc supports cross compiling to all targets from one binary, and we only need to verify it passes semantic analysis only on ARM/linux, and other predefined version combinations.

**Comment by ibuclaw** [comment]
Adding some hidden/internal dmd switch to override predefined versions with an explicit list of conditionals would probably suffice as well.

```
dmd -o- \
  --x-predefined-version-list=AArch64,Linux,Posix,HardFloat,CRuntime_Gcc,CppRuntime_Gcc \
  druntime/src/**.d
```

**Comment by jacob-carlborg** [comment]
Currently LDC does not include all the above mentioned architectures. That should only be a configuration change necessary to enable additional architectures.

**Comment by ibuclaw** [comment]
Only the following are high priority targets to check:
```
aarch64-none-linux-gnu
arm-linux-gnueabi
i586-unknown-freebsd
i686-pc-linux-gnu
powerpc64-unknown-linux-gnu
powerpc64le-unknown-linux-gnu
sparc-sun-solaris2.11
x86_64-pc-linux-gnu
```

**Comment by jacob-carlborg** [comment]
SPARC is one of the architectures that is currently not included in LDC. Here's a list of all the architectures in LDC 1.27.0:

```
  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc32le    - PowerPC 32 LE
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
```

**Comment by PetarKirov** [comment]
> Broke every supported Linux platform.

@ibuclaw can you please share the error that you got for at least one linux platform? Because I reviewed the code again and I still couldn't see find anything wrong with it. (I thought there was an `else static assert (0, "Unsupported platform");` or similar, but there wasn't.)

> Don't merge ANY new Linux bindings unless it supports all of the following:

In principle I agree that we should strive to have complete bindings, but I don't understand what's wrong with an incremental approach either.

**Comment by ljmf00** [comment]
> > Is it possible to upstream some tests?
> 
> It's easy to run tests through emulation using Docker and QEMU: `docker run --platform "linux/$ARCH"`.

I think it would be a good step to implement some simple tests to avoid merging not so clear broken changes.

**Pull request merged**
