### PR TITLE
moveEmplace: optimise and make it betterC friendly

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please also update [the Phobos copy](https://github.com/dlang/phobos/blob/2f030ebbd947c3fed874b3884ca40c793f766dfe/std/algorithm/mutation.d#L1414) as wells they don't get out of sync.

**Comment by 9il** [comment]
btw, why Phobos just does not imports core.lifetime?

**Comment by 9il** [comment]
https://github.com/dlang/phobos/pull/6964

**Comment by thewilsonator** [comment]
Phobos has a check for no internal pointers or something that can't be in druntime because it depends on too much of phobos.

**Comment by 9il** [comment]
Is it this because of optimization reasons?

**Comment by thewilsonator** [comment]
No, its because druntime cannot depend on phobos.

**Comment by 9il** [comment]
Yes, but phobos can depend on druntime. Why not to use public imports?

**Comment by jacob-carlborg** [comment]
> Yes, but phobos can depend on druntime. Why not to use public imports?

Because the implementation is not the same.

**Comment by wilzbach** [comment]
Druntime would need this to match the Phobos implementation: https://github.com/dlang/druntime/pull/2447

**Comment by 9il** [comment]
I closed it because of the same change in Phobos fails.

**Pull request closed without merging**
