### PR TITLE
Revert "core.thread refactor: osthread module"

### PR DESCRIPTION
**Pull request by Geod24**
Reverts dlang/druntime#2689

Because it apparently broke DMD test suite.

### CODE REVIEW

**Comment by Geod24** [comment]
CC @thewilsonator @baziotis

**Comment by Geod24** [comment]
@thewilsonator : Can we merge this ?

**Comment by rainers** [comment]
A bit too late, but https://github.com/dlang/druntime/pull/2801 should fix the issue, too.

**Comment by thewilsonator** [comment]
Thanks, but even if it does we, should enable the azure pipelines for druntime to test it anyway.

**Comment by baziotis** [comment]
> A bit too late, but #2801 should fix the issue, too.

TBH, I didn't have the time to look thoroughly what the problem was, but #2689 did not change any code. I see that yours does a small change. Which makes me think about how the problem arose in the first place and why it didn't happen with the previous.

**Comment by thewilsonator** [comment]
Possibly slack layout, it should be pretty simple to revert this once the azure pipelines are set up for druntime.

**Comment by thewilsonator** [comment]
@baziotis Azure pipelines are now set up, could you please reopen another PR. it seems that this can't be simply reverted due to merge conflicts.

**Comment by baziotis** [comment]
Good! Yes, I assume tomorrow I will have time.

**Pull request merged**
