### PR TITLE
fix Issue 19861 - core.cpuid reports the wrong number of threads

### PR DESCRIPTION
**Pull request by rainers**
do not use i7 detection on AMD processors
use cpuid 0x8000_001E to detect the number of threads per core

It seems AMD uses the term "core" for "logical cores" or threads, too.

### CODE REVIEW

**Comment by rainers** [comment]
@FraMecca This worked for an AMD Ryzen, could you check it on your system, too?

**Comment by thewilsonator** [comment]
```
Enforce whitespace before opening parenthesis
--
  | grep -nrE "\<(for\|foreach\|foreach_reverse\|if\|while\|switch\|catch\|version)\(" $(find src -name '*.d') ; test $? -eq 1
  | src/core/cpuid.d:949:            version(GNU) asm pure nothrow @nogc {
  | posix.mak:383: recipe for target 'style_lint' failed
```

**Comment by rainers** [comment]
Anyone else with an AMD processor who can try this? Running and verifying this should be enough:
```
import core.cpuid;
import core.stdc.stdio;

void main()
{
    printf("coresPerCPU: %d\n", coresPerCPU);
    printf("threadsPerCPU: %d\n", threadsPerCPU);
}
```
Do we know whether there is an AMD used by any CI?

Parallel marking relies on this information, so would be good to have this in before the next release.

**Comment by JinShil** [comment]
> Anyone else with an AMD processor who can try this?

cc @baziotis

**Comment by baziotis** [comment]
I have an AMD Ryzen 7 1700. It is 8-core CPU, with 2 threads per core.
But I get:
```
coresPerCPU: 16
threadsPerCPU: 1
```
`lscpu` data:
```
CPU(s):                    16
Thread(s) per core:  2
Core(s) per socket:  8
```

**Comment by rainers** [comment]
>  have an AMD Ryzen 7 1700. It is 8-core processor, with 2 threads per core.
> But I get:
> coresPerCPU: 16
> threadsPerCPU: 1

Thanks for testing. I guess this is without this patch? With the patch it should be correct (8/16), but unfortunately your CPU is exactly the same I've been trying it on.

**Comment by baziotis** [comment]
> but unfortunately your CPU is exactly the same I've been trying it on.
What are the odds..

> I guess this is without this patch? With the patch it should be correct (8/16)
Yes and yes.

**Comment by rainers** [comment]
Rebased on stable as this is important for parallel marking to work on AMD systems.
I added a test to print out cpuid values, mostly to see if there is an AMD processor in our test fleet.

**Comment by rainers** [comment]
auto tester redmond reports dubious values for Intel Core2, too:
```
processor: Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz
threadsPerCPU:    1
coresPerCPU:      4
```

**Comment by FraMecca** [comment]
Sorry for the delay. It works on my machines.

**Comment by rainers** [comment]
> Sorry for the delay. It works on my machines.

Thanks for testing. I'll remove the verbose output of all the flags from the test.

**Comment by thewilsonator** [comment]
this good to go?

**Comment by rainers** [comment]
> this good to go?

I think so. The bad result for Intel Core2  is another issue, but it is a pretty old CPU (released 2008).

**Pull request merged**
