### PR TITLE
Add rusage struct for musl

### PR DESCRIPTION
**Pull request by hatf0**
Apparently I don't know how to use git. This is the non-screwed up version of pull #2486, which I accidentally managed to squash with another commit.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
> Apparently I don't know how to use git

The simplest thing is to not add new commits but instead amend the existing one:

1. Make your changes as usual and stage them
2. Amend the commit using: `git commit --amend`
3. Force push the branch to update the pull request: `git push <remote> <branch name> -f` where `<remote>` is the name of the remote, usually "origin", and `<branch name>` is the name of the branch

**Comment by ZombineDev** [comment]
@hatf0 The tests are failing due to some trailing whitespace. Can you fix it and amend the commit?

**Comment by hatf0** [comment]
Fixed the whitespace issue, should be ready to merge. @ZombineDev

**Comment by ZombineDev** [comment]
> Fixed the whitespace issue, should be ready to merge.

Yep, everything is in order, thanks for your contribution!

**Pull request merged**
