### PR TITLE
fix Issue 15886 - Add an uncaught exception handler

### PR DESCRIPTION
**Pull request by CyberShadow**
https://issues.dlang.org/show_bug.cgi?id=15886

I'm not sure how to do the win32 part. @llucax?

### CODE REVIEW

**Comment by CyberShadow** [comment]
For some reason the exception passed to the handler doesn't have a stack trace (when printed with `_d_print_throwable`), even though `_d_createTrace` is called on the object. Not sure why. @Walte

**Comment by llucax** [comment]
> I'm not sure how to do the win32 part. @llucax?

If you are asking me about win32, you are barking at the wrong tree :)

**Comment by llucax** [comment]
So in Linux, if no special handler is used, `abort()` is called but **after** the stack was unwound?

**Comment by CyberShadow** [comment]
> If you are asking me about win32, you are barking at the wrong tree :)

Ah, git-blame pointed me to https://github.com/D-Programming-Language/druntime/commit/04e29d17959a8e14a8b2f5c06dfdf72f87f9206a, sorry. @donc? :)

> So in Linux, if no special handler is used, abort() is called but after the stack was unwound?

Well, if there are no exception frames, there is nowhere to unwind to. Normally there is a top-level frame in `_d_run_main`, which can be disabled by setting `rt_trapExceptions` to 0.

**Comment by Marenz** [comment]
> So in Linux, if no special handler is used, abort() is called but after the stack was unwound?

As far as I can tell that is not true, output of a small test:

```
(gdb) break _d_run_main
(gdb) set rt_trapExceptions = 0
(gdb) cont
Continuing.

uncaught exception
dwarfeh(224) fatal error

Program received signal SIGABRT, Aborted.
0x00007ffff740fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff740fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff74130d8 in __GI_abort () at abort.c:89
#2  0x0000000000423a56 in _d_throwdwarf ()
#3  0x0000000000421bb8 in _d_assert ()
#4  0x0000000000421918 in main.__assert() ()
#5  0x00000000004218ae in D main () at main.d:15
#6  0x00000000004238af in rt.dmain2._d_run_main() ()
#7  0x0000000000423827 in rt.dmain2._d_run_main() ()
#8  0x000000000042386b in rt.dmain2._d_run_main() ()
#9  0x0000000000423827 in rt.dmain2._d_run_main() ()
#10 0x000000000042374a in _d_run_main ()
#11 0x0000000000421968 in main ()
```

Not sure why I see `dwarfeh(224) fatal error` though

**Comment by CyberShadow** [comment]
> Not sure why I see dwarfeh(224) fatal error though

https://github.com/D-Programming-Language/druntime/blob/master/src/rt/dwarfeh.d#L223-L224

which calls

https://github.com/D-Programming-Language/druntime/blob/master/src/rt/dwarfeh.d#L805-L809

**Comment by Marenz** [comment]
Ah, makes sense now.

**Comment by Marenz** [comment]
@MartinNowak trying a direct hilight

**Comment by rainers** [comment]
> I'm not sure how to do the win32 part.

SetUnhandledExceptionFilter will probably help, see https://msdn.microsoft.com/en-us/library/ms680634.aspx

**Comment by CyberShadow** [comment]
> SetUnhandledExceptionFilter will probably help, see https://msdn.microsoft.com/en-us/library/ms680634.aspx

Thanks. That's probably going too far for this pull request, so it's probably better to declare that this feature is unsupported on Win32.

**Comment by CyberShadow** [comment]
A test would be much easier to write once https://github.com/dlang/druntime/pull/1538 is in.

**Comment by Burgos** [comment]
See how I got the test for the same functionality, albeit only for dwarfeh: https://github.com/dlang/druntime/pull/1673/files#diff-eb6feae96258d70e7e610bffc21427bc

I was not aware of this PR when writing my own, I guess we shouldn't leave them too long to rot :(.

**Comment by CyberShadow** [comment]
This would be nice to have for certain situations but does need some more thinking (especially how to approach the platform disparity).

**Pull request closed without merging**
