### PR TITLE
fix Issue 22744 - ImportC: builtins defined in __builtins.di cause un…

### PR DESCRIPTION
**Pull request by WalterBright**
…defined symbol linker errors

Making them templates makes the import "header only".

### CODE REVIEW

**Comment by WalterBright** [comment]
```
Test compilable/test6461.sh failed. The logged output:
 ... compilable\test67.d            ()
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `a.obj` has magic = 6202, should be 8664
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `a_1_149.obj` has magic = 6202, should be 8664
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `tmpl_2_309.obj` has magic = 6202, should be 8664
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `object_3_5ad.obj` has magic = 6202, should be 8664
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `object_4_9ff.obj` has magic = 6202, should be 8664
D:\a\1\dmd\test\test_results\compilable\test6461a.lib: Error: MS-Coff object module `object_5_5e9.obj` has magic = 6202, should be 8664
```

It makes no sense that this has anything to do with this PR.

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
@RazvanN7 is there something else in druntime causing these errors?

**Comment by RazvanN7** [comment]
Do you have the latest version of druntime? @MoonlightSentinel has been doing some MS-Coff patches recently so there might be some branch checkout mismatches.

**Comment by WalterBright** [comment]
trying a rebase...

**Comment by RazvanN7** [comment]
That seems to have fixed it. When in doubt, rebase...

**Comment by huglovefan** [comment]
this might be a separate issue but it still causes a link error if you use `dmd -i` (include-imports mode)

```
% cat main.c
int main() { double x = __builtin_inf(); }
% work/result/bin/dmd -run main.c
% work/result/bin/dmd -i -run main.c
ld.lld: error: undefined symbol: _D10__builtins__T13__builtin_infZQqFNaNbNiNfZd
>>> referenced by main.c
>>>               main.o:(main)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
```

same thing affects D code if you have templates in a .di file and use `-i`

**Comment by WalterBright** [comment]
@huglovefan as issue is not specific to this PR or ImportC, please file a bugzilla issue for it.

**Pull request merged**
