### PR TITLE
fix spurious crashes/freezes due to corruption in GC.realloc caused by #2430

### PR DESCRIPTION
**Pull request by rainers**
while debugging #2436 I noticed an issue introduced by #2430.

### CODE REVIEW

**Comment by rainers** [comment]
Maybe this bug has frozen buildkite as an assertion triggered in the GC causes the application to freeze in a recursive lock.

**Comment by wilzbach** [comment]
> Maybe this bug has frozen buildkite

Jobs have a default timeout of an hour and agents are constantly freshly provisioned and decommissioned. However, the provisioning takes a bit, so it always takes about 15 minutes for new agents to start.

**Comment by rainers** [comment]
> Jobs have a default timeout of an hour

This one's running for 5 hours now: https://buildkite.com/dlang/druntime/builds/969

**Comment by thewilsonator** [comment]
All green now.

**Pull request merged**
