### PR TITLE
Revert "Revert "Add SO_REUSEPORT constant""

### PR DESCRIPTION
**Pull request by wilzbach**
This should be pulled once Vibe.d has changed and Jenkins is green :)

### CODE REVIEW

**Comment by ZombineDev** [comment]
@s-ludwig Can we upgrade diet-ng and dub to the latest vibe.d version? The use of an older vibe.d is a blocker for this PR.

**Comment by s-ludwig** [comment]
The updated DUB should already be in the latest 2.076.0-rc.1. I'll upgrade the example in diet-ng to use 0.8.x.

**Comment by ZombineDev** [comment]
Thanks, so I guess when the official release for `2.076.0` is tagged, a new (non beta) release for dub will be tagged too and Jenkins will pick it up.

**Comment by s-ludwig** [comment]
Just noticed that Martin has tagged the release just a few minutes ago. The new version should now be available.

**Comment by ZombineDev** [comment]
@s-ludwig unfortunately the new release broke Jenkins :/

**Comment by wilzbach** [comment]
Rebased this PR to the latest master, s.t. Jenkins gets retriggered and we hopefully can move on (:

**Comment by wilzbach** [comment]
```
../../.dub/packages/vibe-d-0.8.0/vibe-d/core/vibe/core/drivers/libevent2.d(365,63): Error: vibe.core.drivers.utils.SO_REUSEPORT at ../../.dub/packages/vibe-d-0.8.0/vibe-d/core/vibe/core/drivers/utils.d(53,10) conflicts with core.sys.posix.sys.socket.SO_REUSEPORT at /var/lib/jenkins/dlang_projects@2/distribution/bin/../imports/core/sys/posix/sys/socket.d(306,13)
```

It looks like we need to bump the vibe.d version used @ DUB.

**Comment by wilzbach** [comment]
Rebased to master. As there have been a couple of releases of vibe-d, this should most likely pass now.

**Comment by wilzbach** [comment]
>  This commit cannot be be built

Looks like Jenkins has troubles with PRs from `dlang` branches -> https://github.com/dlang/druntime/pull/2036

**Pull request closed without merging**
