### PR TITLE
New ctfe: update druntime

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by schveiguy** [comment]
@UplinkCoder I'm assuming this is just a merge for latest code from master? How do I interpret all the automated testing failures?

**Comment by UplinkCoder** [comment]
@schveiguy 
For some reason the makefile is busted....
 ../dmd/generated/linux/release/64/dmd: Command not found

**Comment by wilzbach** [comment]
> ../dmd/generated/linux/release/64/dmd: Command not found

Your CTFE branch at DMD probably doesn't contain the move to `ddmd` in which that was updated?

**Comment by joakim-noah** [comment]
Looks like you need to rebase?

**Comment by MartinNowak** [comment]
Let's not do this via PRs as we need to update all branches in lockstep.

**Pull request closed without merging**
