### PR TITLE
properly fix failing test with missing CLOCK_BOOTTIME support

### PR DESCRIPTION
**Pull request by MartinNowak**
- detect older kernel versions in makefile
- disable ClockType.bootTime in tests

### CODE REVIEW

**Comment by MartinNowak** [comment]
Needed to fix Travis-CI tests for ddmd.

**Comment by schveiguy** [comment]
I don't like how the normal (non-test) code is affected by the change. Can you just change it so the unit test skips over that clock?

**Comment by MartinNowak** [comment]
> Might be overkill, though, if this stays the only kink of this sort. I'd imagine the capabilities of other systems to evolve similarly from time to time, though?

I don't, clock APIs are around since ages.

**Comment by MartinNowak** [comment]
> I don't like how the normal (non-test) code is affected by the change. Can you just change it so the unit test skips over that clock?

Done

**Comment by schveiguy** [comment]
LGTM

**Comment by ibuclaw** [comment]
> Needed to fix Travis-CI tests for ddmd.

I wonder why when I just tested gdc-4.9.3 right now that I didn't have this problem...

**Comment by MartinNowak** [comment]
> Possibly because your test ended up running on a box with a newer kernel?

Not sure either, they all use the same kernel.
https://travis-ci.org/D-Programming-Language/dmd/jobs/77026325#L13

**Comment by ibuclaw** [comment]
> Possibly because your test ended up running on a box with a newer kernel?

It's not that.
gdc (pass): https://travis-ci.org/D-Programming-Language/dmd/jobs/77179955#L13
dmd (fail): https://travis-ci.org/D-Programming-Language/dmd/jobs/77179952#L13

**Comment by ibuclaw** [comment]
Hmm... just restarted it and it looks like it will pass now.

**Comment by MartinNowak** [comment]
> Hmm... just restarted it and it looks like it will pass now.

works: https://travis-ci.org/MartinNowak/test_clock_getres/builds/77230921
fails: https://travis-ci.org/MartinNowak/test_clock_getres/builds/77231498

Since the tests are running on the old fully virtualized environment (VirtualBox or so) it might be a lack of support in VirtualBox or the host kernel. Let's merge this and go on.

**Comment by MartinNowak** [comment]
ping

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
