### PR TITLE
Demangle consumes megabytes of memory for each unsucessful demangle

### PR DESCRIPTION
**Pull request by denizzzka**
This PR shows this behaviour

### CODE REVIEW

**Comment by denizzzka** [comment]
I can't figure out where is bug. This happens when RAM amount are not large and then at the one moment OverflowException handler calls out of memory exception while buf is grows and grows.

core.demangle looks as exception-driven and statefull code.. :- (

**Comment by ibuclaw** [comment]
> I can't figure out where is bug. This happens when RAM amount are not large and then at the one moment OverflowException handler calls out of memory exception while buf is grows and grows.
> 
> core.demangle looks as exception-driven and statefull code.. :- ( 

Yeah. The backtrace printer for uncaught throwables uses try/catch IIRC for attempting to demangle found function names. Which doesn't bode well in some scenarios.

**Comment by denizzzka** [comment]
> The backtrace printer for uncaught throwables uses try/catch IIRC for attempting to demangle found function names.

Yea, code must be changed to avoid exceptions. Maybe just replace exceptions by struct like { errStatus; value; }

**Comment by rainers** [comment]
I just tried your test cases: there are only the regular 4k allocations once it starts unpacking, nothing unexpected, on run.dlang.io or Windows. You can avoid these allocations if you pass a destination buffer to `demangle`.

**Comment by denizzzka** [comment]
> I just tried your test cases

This is first part of unittests from core.demangle what fails on small system at step i == 2. When this step occurs buf needs 1Mb * 2 in Overflow handler.

Maybe previous unittests also consume buf before to get into this condition

**Pull request closed without merging**
