### PR TITLE
Add WebAssembly definitions to src/core/stdc

### PR DESCRIPTION
**Pull request by dkorpel**
Trying to revive https://github.com/dlang/druntime/pull/2738, splitting it up to make it easier to review. @skoppe

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by dkorpel** [comment]
> still might be worth using the technically correct label from the get go.

This decision was explained in the original PR:

> The one controversial thing about this pull request is the fact that the WASI bindings are versioned as `WebAssembly`. I have done this for several reasons:
> 
>   1. targeting WASI is a simple as compiling for WebAssembly and linking with the [WASI's libc](https://github.com/CraneStation/wasi-libc). (See [example for C](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md#from-c)).
> 
>   2. by not using any of the libc functions you are effectively targeting the web. (if you compile with `ldc --mtriple=wasm32-unknown-unknown-wasm` and not call any of druntime functions, nothing gets linked in. No `rt_init()`, nothing.)
> 
> 
> In time more WebAssembly runtimes will emerge (e.g. intel's [wasm-micro-runtime](https://github.com/intel/wasm-micro-runtime)), which would necessitate splitting the bindings into WASI and others.

I don't mind changing it, I just want to get something working in so my code doesn't hit static asserts when compiling to WebAssembly.

**Comment by adamdruppe** [comment]
The reasoning from the original PR seems to argue in favor of calling it version(WASI)... it even mentions there's other runtimes already...

Sure, if you don't link it in, you don't use it - that's why I don't think it is *especially* important - but still.

**Comment by dkorpel** [comment]
I changed `version (WebAssembly)` to `version (WASI)`

**Review by Geod24 — APPROVED** [review]
Let's move ahead with this, it's not like it is going to break anyone's code

**Comment by adamdruppe** [comment]
yeah if we need to rename WASI that's easy enough to find/replace all later since it won't be mixed with anything else.

**Comment by skoppe** [comment]
Many thanks for this.

@adamdruppe was right, these should not be versioned under `version(Webassembly)`. However, neither on `version(WASI)`, but rather `version(CRuntime_WASI)`.

See https://github.com/dlang/dmd/pull/10778#issuecomment-584024552 for backstory.

In short:

WASI is the WebAssemby System Interface. It provides a set of function similar in spirit to posix, but incompatible none-the-less.

It is [wasi-libc](https://github.com/WebAssembly/wasi-libc) that provides a posix like interface on top of WASI.

For that we have added `CRuntime_WASI`.

So, any libc things should be versioned under `CRuntime_WASI`.

**Comment by skoppe** [comment]
Also note that the `wasm` branch is more up to date https://github.com/skoppe/druntime/tree/wasm

Although geared for LDC.

**Comment by adamdruppe** [comment]
i thought the CRUntime_xxx ones were reserved.... i guess even if it is, the compiler should be the one setting it anyway based on the triple.

**Comment by ibuclaw** [comment]
> i thought the CRUntime_xxx ones were reserved.... i guess even if it is, the compiler should be the one setting it anyway based on the triple.

CRuntime itself isn't reserved so all _xxx variations of it aren't either (however CRuntime_Glibc_or_something would be reserved).

**Comment by adamdruppe** [comment]
cool, well easy find/replace here then. follow up pr lol

**Pull request merged**
