### PR TITLE
Adds c_long and c_ulong for bare-metal ARM 32-bit platform

### PR DESCRIPTION
**Pull request by denizzzka**
Based on information from http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0041c/ch03s02s02.html

### CODE REVIEW

**Comment by denizzzka** [comment]
Is such a PR appropriate or is our goal is to create a separated runtime for bare metal?

**Comment by denizzzka** [comment]
Okay, too global a task if think more deeply.

**Comment by ibuclaw** [comment]
There is version FreeStanding that could be used.

**Comment by denizzzka** [comment]
> There is version FreeStanding that could be used.

Thanks! This is what I was looking for!

**Pull request closed without merging**
