### PR TITLE
Fix issue 15959 additional fixes

### PR DESCRIPTION
**Pull request by qchikara**
https://issues.dlang.org/show_bug.cgi?id=15959

A number of simple replaces,
which are required by x64 Win32 programs.

Mostly in this form:
DWORD/int/uint/ -> DWORD_PTR/ULONG_PTR/INT_PTR

This should make no change in x86 programs.

### CODE REVIEW

**Comment by qchikara** [comment]
I've got this by boring repetition of greps. (sigh)

**Comment by qchikara** [comment]
Oops.
> which requires for x64 Win32 programs.
===> which are required by x64 Win32 programs.

**Comment by qchikara** [comment]
rebased

**Comment by rainers** [comment]
I haven't verified every change, but I trust you on these. Thanks for doing this.

**Comment by rainers** [comment]
Auto-merge toggled on

**Pull request merged**
