### PR TITLE
Fix Issue 22107 - [scope][dip1000] Can't .dup an array of structs wit…

### PR DESCRIPTION
**Pull request by CyberShadow**
…h impure copy constructor

### CODE REVIEW

**Comment by CyberShadow** [comment]
CC @dkorpel

**Comment by dkorpel** [comment]
I thought `scope` would be inferred now [issue 21209](https://issues.dlang.org/show_bug.cgi?id=21209) is fixed.

Is `dup` still `@safe` on structs that have a `@safe` but a non-`scope` copy-constructor with this change?

**Comment by CyberShadow** [comment]
> I thought `scope` would be inferred now [issue 21209](https://issues.dlang.org/show_bug.cgi?id=21209) is fixed.

I didn't see that ... but, I can reproduce the issue even with DMD `master`, if it helps.

> Is `dup` still `@safe` on structs that have a `@safe` but a non-`scope` copy-constructor with this change?

Sorry, not sure how to test this.

**Comment by dkorpel** [comment]
> Sorry, not sure how to test this.

Actually, since the array is `scope`, its elements are never `scope`, so it doesn't matter. The only tricky case I can think of is:
```D
@safe:
struct S
{
    int x;
    int* y;

    this(ref S old)
    {
        y = &old.x;
    }
}

void main()
{   
    S[] oldArr = new S[1]; 
    S[] newArr = oldArr[].dup;
    assert(newArr[0].y == &oldArr[0].x); // allowed since it's on the heap

    S[1] oldArr1; // on the stack
    S[] newArr1 = oldArr1[].dup;  // now it's not allowed
}
```
This is horrible code, but the first case is technically valid.

**Comment by CyberShadow** [comment]
Well, I don't know what's going on here, then. Especially considering that the "fix" is in the CTFE helper, and none of this pertains CTFE.

**Comment by CyberShadow** [comment]
> ```d
>     S[] newArr1 = oldArr1[].dup;  // now it's not allowed
> ```

And now it is allowed with the changes in this PR, which I understand is incorrect. But then why wasn't this flagged as an error somewhere else?

**Comment by dkorpel** [comment]
> Especially considering that the "fix" is in the CTFE helper, and none of this pertains CTFE.

The `if (__ctfe)` branch is still taken as far as escape analysis is concerned

**Comment by dkorpel** [comment]
> And now it is allowed with the changes in this PR, which I understand is incorrect. But then why wasn't this flagged as an error somewhere else?

I think the fact that it didn't compile is completely accidental: it didn't compile for the same reason the correct case in this PR's unittest didn't compile. My copy constructor example is actually invalid, you're not allowed to assign a pointer to a `ref` to a member. I think that's a manifestation of [issue 20245](https://issues.dlang.org/show_bug.cgi?id=20245).

**Review by dkorpel — APPROVED** [review]

**Comment by dkorpel** [comment]
I just noticed that this is also needed to make druntime unittests compile with https://github.com/dlang/dmd/pull/12010.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
