### PR TITLE
[stable] core.atomic: Make type repainting in atomicLoad cheaper

### PR DESCRIPTION
**Pull request by kinke**
Pinging @TurkeyMan.

### CODE REVIEW

**Comment by TurkeyMan** [comment]
How does this make it cheaper? Why isn't this identical?
I'm not on board with this change... I specifically designed against instantiations of the implementation functions with types like that.

**Comment by TurkeyMan** [comment]
On I get it, because `move` is rubbish...
We need to fix `move`... it's my #1 slot for worst problem in D right now.

**Comment by kinke** [comment]
> On I get it, because move is rubbish...

Exactly, and I don't see how `T` is better suited for the internal implementation than the `TailShared!T`; it's not like you'd use an integer type of matching size here or something like that.

The actual reason is that LDC's druntime testrunner wouldn't link due to undefined `move` template instantiations without this; this rewrite hides that problem at least. ;)

**Comment by TurkeyMan** [comment]
Well, `TailShared` should be eradicated somehow, and I'm trying to isolate that as much as possible for the time being.
I guess I can tolerate this patch though, since it's contained in a function that shouldn't exist anyway (see the comment immediately above). It still upsets me :/

**Comment by PetarKirov** [comment]
@wilzbach is @dlang-bot taking a day off? :D

image

**Pull request merged**
