### PR TITLE
test_runner can run all tests as well as individual modules

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
What's the purpose of this?

**Comment by atilaneves** [comment]
Purpose: making the test runner better - I for one don't think we should have as much logic as we do in the makefiles

**Comment by joakim-noah** [comment]
Does running all tests actually work?  I had to [disable two test blocks in rt.lifetime when running all the tests in a single process](https://gist.github.com/joakim-noah/069036835dd92cf648a8219bfe4d68c3#file-druntime_1-0-0_ldc_arm-L32), which this PR enables but doesn't exercise in the auto-tester.

**Comment by atilaneves** [comment]
No, running all tests in the same process doesn't work. I get a failure in std.stdio, but without this patch we wouldn't even know that.

**Comment by MartinNowak** [comment]
> No, running all tests in the same process doesn't work. I get a failure in std.stdio, but without this patch we wouldn't even know that.

But it's more likely to be a bad test than a real problem ;).

**Pull request merged**
