### PR TITLE
Refactor stdcpp tests makefile

### PR DESCRIPTION
**Pull request by TurkeyMan**
Improve the stdcpp test makefile.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Why is this changing windows stuff when the title is "Add posix `std::string` tests"? Apart from win32 everything else is green.

**Comment by TurkeyMan** [comment]
Because it was sitting on top (the comment said it depended on the windows PR)
I rebased to be self-contained. It's a nice little refactor.

**Comment by thewilsonator** [comment]
Awesome, lets get this ball rolling.

**Comment by TurkeyMan** [comment]
Now the tests are split into capability sets; we'll need to work out how to detect the capabilities of the build machines so they can run the proper sets of tests...

**Pull request merged**
