### PR TITLE
CircleCi: merge PRs with upstream branch

### PR DESCRIPTION
**Pull request by wilzbach**
Similar to https://github.com/dlang/phobos/pull/4955.

In general it makes a lot of sense to merge to merge with the upstream branch, s.t. changes are always tested as they would be merged  (DAutoTest and auto-tester behave in the same way).

I added some minor updates to the script as well, e.g. always using `--depth 1` caused a stupid error at Phobos when done with the tools repo.

### CODE REVIEW

**Comment by wilzbach** [comment]
Hmm why isn't CircleCi running at all?
Can someone with merge rights check whether it's due to the settings?

> https://circleci.com/gh/dlang/druntime/edit#advanced-settings

Seems to be very similar to https://github.com/dlang/phobos/pull/4850#issuecomment-265708782

**Comment by schveiguy** [comment]
> Can someone with merge rights check whether it's due to the settings?

I see the setting "Build forked pull requests" is off, I don't see a setting for "Permissive building of forked pull requests"

**Comment by wilzbach** [comment]
> I see the setting "Build forked pull requests" is off, I don't see a setting for "Permissive building of forked pull requests"

So then I guess enabling "Build forked pull requests" would be the solution?
However I don't know how it got disabled :O, but we definitely had it in the past (e.g. the CodeCov results are generated on CircleCi)

**Comment by schveiguy** [comment]
> enabling "Build forked pull requests" would be the solution

Did so. We'll see if it helps.

**Comment by wilzbach** [comment]
> Did so. We'll see if it helps.

Yes - thanks a lot!

image

**Comment by andralex** [comment]
Have no idea what I'm doing, but heck - what's the worst that could happen?

**Pull request merged**
