### PR TITLE
Use new __traits(classInstanceAlignment)

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Review by ljmf00 — APPROVED** [review]

**Comment by ljmf00** [comment]
The issue refers to `druntime` component. Maybe it should be `phobos` or mark this as auto-close for the bot to grab it.

**Comment by ljmf00** [comment]
Humm, `_d_newclass` needs some tweaks to make GC/malloc allocate with the correct alignment, so we shouldn't close it yet.

**Comment by kinke** [comment]
Yep exactly, the GC part should be the last missing piece of that (druntime) issue. Phobos was already changed to use druntime's `classInstanceAlignment` trait, so https://github.com/dlang/phobos/pull/8459 wasn't actually needed to fix `std.typecons.scoped()`.

**Comment by ljmf00** [comment]
Ok, so, I think we can merge this, then.

**Pull request merged**
