### PR TITLE
Deprecate TypeInfo.init

### PR DESCRIPTION
**Pull request by aG0aep6G**
As planned.

### CODE REVIEW

**Comment by schveiguy** [comment]
LGTM.

**Comment by ZombineDev** [comment]
LGTM too, but can you add a deprecation message that tells the users to use `initializer`?

**Comment by schveiguy** [comment]
A deprecation message would be useful, and costs basically nothing. I think it's a good idea.

**Comment by aG0aep6G** [comment]
> can you add a deprecation message that tells the users to use initializer?

done

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
