### PR TITLE
Much more complete core.sys.windows.security

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by John-Colvin** [comment]
Pretty sure the buildkite failures aren't my fault.

It seems like we have enough flakey test systems now that at least one is randomly malfunctioning every time I look.

**Comment by Laeeth** [comment]
I wonder what we could do to help get D build systems into top notch condition.

**Comment by John-Colvin** [comment]
> Still a WIP ?

no, not any more

**Comment by Geod24** [comment]
Alright, can you add a changelog entry (Just saying more definition were added is enough) ? Sorry for the back & forth.

**Comment by John-Colvin** [comment]
> 
> 
> Alright, can you add a changelog entry (Just saying more definition were added is enough) ? Sorry for the back & forth.

done

my fault for not following the process before.

**Comment by Geod24** [comment]
> done

Actually the filename needs to end with [`.dd`](https://github.com/dlang/druntime/blob/master/changelog/README.md)

**Pull request merged**
