### PR TITLE
fix Issue 20227 - "Error: phread_mutex_destroy failed." after fork()

### PR DESCRIPTION
**Pull request by rainers**
clear thread handles and events for parallel marking in child process after fork

might also fix failing tests in https://github.com/dlang/druntime/pull/2802

### CODE REVIEW

**Comment by rainers** [comment]
Should be better rebased to stable?

**Comment by thewilsonator** [comment]
Yes.

**Comment by rainers** [comment]
Done.

**Comment by CyberShadow** [comment]
On Darwin_64_64:
```
Testing forkgc
timelimit -t 10 ./generated/osx/debug/64/forkgc 
core.thread.ThreadError@src/core/thread.d(3093): Unable to load thread state
----------------
timelimit: sending warning signal 15
make[2]: *** [generated/osx/release/64/forkgc.done] Error 143
```

**Comment by rainers** [comment]
Turns out forking under OSX didn't really work at all (when thread handles were needed in the child process). Any more involved program will probably also fail on Linux, e.g. because the chain of threads is invalid.

**Pull request merged**
