### PR TITLE
Mark @nogc attribute for OSX semaphore and pthread functions

### PR DESCRIPTION
**Pull request by p0nce**

### CODE REVIEW

**Comment by schuetzm** [comment]
LGTM

**Comment by ZombineDev** [comment]
LGTM^2

**Comment by schveiguy** [comment]
I think this looks good, but should we do non-osx specific ones too? e.g. https://github.com/p0nce/druntime/blob/master/src/core/sys/posix/pthread.d

**Comment by schveiguy** [comment]
Wow, that seems to have broken things, Looks like there may be some function type issues?

**Comment by joakim-noah** [comment]
OS X changes not needed because of recently merged #1448.

**Comment by p0nce** [comment]
I guess this can be closed then?

**Comment by joakim-noah** [comment]
Depends on whether you want to try and make `core.sys.posix.pthread` `@nogc` too by looking into why it's failing the auto-tester.  It appears that it's breaking some template instantiation that shouldn't have worked in the first place?

**Comment by p0nce** [comment]
Well no I didn't want to do that.

**Pull request closed without merging**
