### PR TITLE
Fix Issue 19008 - core.internal.convert.toUbyte doesn't work on enums

### PR DESCRIPTION
**Pull request by n8sh**
Resubmission of https://github.com/dlang/druntime/pull/2224 to target stable.

### CODE REVIEW

**Comment by n8sh** [comment]
>bash: line 1: ./circleci.sh: No such file or directory

okay...

**Comment by schveiguy** [comment]
@wilzbach I restarted circleci, gets the same error. It doesn't make any sense, as circleci.sh is there for previous steps?

**Comment by nordlow** [comment]
Thanks!

**Comment by wilzbach** [comment]
Not sure what went wrong with CircleCi, but it's definitely unrelated.

**Pull request merged**
