### PR TITLE
Simplify Visual C configuration for -m64/-m32mscoff builds

### PR DESCRIPTION
**Pull request by CyberShadow**
Ping @rainers

### CODE REVIEW

**Comment by MartinNowak** [comment]
I know little to nothing about VC integration. What problem does this pull solve?

**Comment by CyberShadow** [comment]
> I know little to nothing about VC integration. What problem does this pull solve?

Makes it easier to build -m32mscoff Phobos/Druntime, or cross-compile 32-bit to 64-bit.

**Comment by MartinNowak** [comment]
Waiting for @braddr to do something with the auto-tester.

**Comment by wilzbach** [comment]
> Waiting for @braddr to do something with the auto-tester. We really need more people that can maintain the auto-tester, because Brad is a busy person and we too often get stuck.

At mir we combined AppVeyor and Travis to test for Win32,Win64,Linux32,Linux64 and OS X 64 (OS X 32 has been deprecated for a couple of years). 
At [ldc](https://forum.dlang.org/post/hikcbbqqnpvvyirxgzxu@forum.dlang.org) they started to experiment with buildbot. Jenkins also supports distributed building...

**Comment by wilzbach** [comment]
ping @braddr - do you have time to update the auto-tester?

**Comment by Geod24** [comment]
Druntime have been merged into DMD. Please re-submit your PR to `dlang/dmd` repository.

**Pull request closed without merging**
