### PR TITLE
Fix Issue 18247 - core.stdc.math functions that never set errno should be pure

### PR DESCRIPTION
**Pull request by n8sh**
These include:
* ~~cos, sin, tan,~~ [atan](https://linux.die.net/man/3/atan);
* [tanh](https://linux.die.net/man/3/tanh), [asinh](https://linux.die.net/man/3/asinh);
* [frexp](https://linux.die.net/man/3/frexp), [modf](https://linux.die.net/man/3/modf);
* [cbrt](https://linux.die.net/man/3/cbrt);
* [erf](https://linux.die.net/man/3/erf);
* [ceil](https://linux.die.net/man/3/ceil), [floor](https://linux.die.net/man/3/floor), [trunc](https://linux.die.net/man/3/trunc), [round](https://linux.die.net/man/3/round), [rint](https://linux.die.net/man/3/rint), [nearbyint](https://linux.die.net/man/3/nearbyint);
* [copysign](https://linux.die.net/man/3/copysign), nan;
* [fdim](https://linux.die.net/man/3/fdim), [fmax](https://linux.die.net/man/3/fmax), [fmin](https://linux.die.net/man/3/fmin);
* [fabs](https://linux.die.net/man/3/fabs), abs, [fma](https://linux.die.net/man/3/fma);
* fpclassify, isfinite, isinf, isnan, isnormal, [signbit](https://linux.die.net/man/3/signbit);
* [isgreater](https://linux.die.net/man/3/isgreater), [isgreaterequal](https://linux.die.net/man/3/isgreaterequal), [isless](https://linux.die.net/man/3/isless), [islessequal](https://linux.die.net/man/3/islessequal), [islessgreater](https://linux.die.net/man/3/islessgreater), [isunordered](https://linux.die.net/man/3/isunordered).

### CODE REVIEW

**Comment by ibuclaw** [comment]
Are you sure about that? The latter ones seem fine, as they are bit getters/setters.

I don't believe you when you say that cos, sin and tan are pure.

**Comment by n8sh** [comment]
You were right to disbelieve me. On macOS 10.12.6 `man cos` says:

> cos(+-infinity) returns a NaN and raises the "invalid" floating-point exception

[But on Linux](https://linux.die.net/man/3/cos):

> Domain error: x is an infinity
> errno is set to EDOM (but see BUGS). An invalid floating-point exception (FE_INVALID) is raised.
> ...
> Before version 2.10, the glibc implementation did not set errno to EDOM when a domain error occurred.

Will fix. I'll also check the other functions.

**Comment by ibuclaw** [comment]
I still think there are a couple others (tanh, asinh). I'll check against both glibc and gcc how they attribute these functions.

**Comment by n8sh** [comment]
Looking at the glibc sources, [sysdeps/ieee754/dbl-64/s_sin.c](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/dbl-64/s_sin.c;hb=HEAD) contains `#include <errno.h>` and `__set_errno`. In contrast neither of those appear in:
* [sysdeps/ieee754/dbl-64/s_tanh.c](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/dbl-64/s_tanh.c;hb=HEAD)
* [sysdeps/ieee754/dbl-64/s_asinh.c](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/dbl-64/s_asinh.c;hb=HEAD)
* [sysdeps/ieee754/dbl-64/s_atan.c](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/dbl-64/s_atan.c;hb=HEAD)

Neither do `tanh`/`asinh`/`atan` have branches in [sysdeps/ieee754/k_standard.c](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/k_standard.c;hb=HEAD) which implements `errno` setting for a variety of functions.

However if `tanh`, `asinh`, and/or `atan` are sticking points I can remove the `pure` annotation from them.

**Comment by ibuclaw** [comment]
@n8sh - I'll use [gcc](https://github.com/gcc-mirror/gcc/blob/master/gcc/builtins.def) as a reference, math functions that set errno are marked as `MATHFN_ERRNO`

Now, having gone through the list, I can say that of all functions you originally gave should, only one function is listed as setting errno:

- fdim - ✖️
 
Looks like cos, sin, and tan are fine afterall.

**Comment by ibuclaw** [comment]
> Looking at the glibc sources, sysdeps/ieee754/dbl-64/s_sin.c contains #include <errno.h> and __set_errno. In contrast neither of those appear in:

If I was to be pedantic, `tanh()` calls `expm1()`, which _may_ set errno.

https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/ieee754/dbl-64/s_expm1.c;h=3e136e7ee07375d6b7aeafbfe9cafca5412acd12;hb=refs/heads/master

**Comment by n8sh** [comment]
OK, added `pure` back to sin/cos/tan and removed it from fdim.

**Comment by ibuclaw** [comment]
Also [newlib documentation](https://sourceware.org/newlib/libm.html#fdim) is a good point of reference too.

**Comment by n8sh** [comment]
Rebased for [musl](https://github.com/dlang/druntime/pull/2066).

**Pull request merged**
