### PR TITLE
OpenBSD: Add OpenBSD definitions to core.stdc

### PR DESCRIPTION
**Pull request by redstar**
Add OpenBSD definitions to core.stdc.

This is the first part of my changes for OpenBSD.

### CODE REVIEW

**Comment by WalterBright** [comment]
Check the DAutoTest failure?

**Comment by redstar** [comment]
I don't understand the failure. Why is `} else version ( OpenBSD )` an unexpected declaration?

**Comment by redstar** [comment]
With a closer look I found the problem.

**Comment by JackStouffer** [comment]
Why not use the new alias syntax since the old one is (supposedly) scheduled for deprecation?

**Pull request merged**
