### PR TITLE
Important to clean up aggregates too!

### PR DESCRIPTION
**Pull request by TurkeyMan**
Got tripped up by the `__xdtor` thing.

### CODE REVIEW

**Comment by TurkeyMan** [comment]
This is an amendment on a patch that was already merged. Everything was in that prior PR.

**Comment by TurkeyMan** [comment]
Also, I can't produce a working test case for aggregate destruction, because it's broken (a separate issue).

**Comment by kinke** [comment]
AFAICT, we'd need yet something similar to `__xdtor` for `extern(C++)` classes, mangled as C++ dtor and calling what `__xdtor` would alias (calling its own extern(C++) dtor implemented in D and/or destructing its own fields in reversed order) but then also calling its base class' C++ dtor (cleaning up itself and its bases recursively this way).

Only if the dtor is implemented in D that is; if it's just forward declared and the implementation in C++, it forward-declares the external real C++ dtor, and there should be no need for any D destructors (__dtor, __fieldDtor, __aggrDtor, __xdtor).

**Comment by TurkeyMan** [comment]
Yes, I wrote all those things on the forum.
But we don't have that yet... so for the time being, just pull this and fix the bug ;)

**Comment by TurkeyMan** [comment]
I just pushed https://github.com/dlang/dmd/pull/8274 to fix the destructor bug, which means this is now required to do the right thing.

**Comment by TurkeyMan** [comment]
dlang/dmd#8274 is merged now, so `destroy()` is now broken until this merges...

**Comment by TurkeyMan** [comment]
Gah. Okay, I added the aggregate checks.

**Comment by TurkeyMan** [comment]
If you want to bless the other one, then the tests can attempt to run ;)

**Comment by TurkeyMan** [comment]
Do I need to do anything to rebuild against new DMD master?

**Comment by TurkeyMan** [comment]
I notice that there is a button to trigger a circle-ci rebuild if you have permission...

**Comment by TurkeyMan** [comment]
Huzzah!

**Pull request merged**
