### PR TITLE
Alternate precise GC implementation

### PR DESCRIPTION
**Pull request by rainers**
This version of the precise GC saves type info in allocated memory.

The memory footprint of this version is different from the original GC (https://github.com/D-Programming-Language/druntime/pull/1022) which allocated a pointer bitmap alongside every memory pool (one bit per size_t):
- one bit per possible allocation block (i.e. per 16 bytes for standard pools, per 4kB for large object pools)
- if the allocation block is not NO_SCAN or must be scanned conservatively, one pointer at the end of the allocation block, i.e. only adds additional memory if the allocation size is just below a power of 2, but then the size doubles.

Some more notes:
- The runtime overhead for allocation is less because no pointer bitmap has to be filled.
- The mark phase has to go through an indirection to get the pointer bitmap of a type, but it now has the abitlity to only scan the memory actually requested and skip padded memory
- The RTInfo can contain a delegate to call instead of standard marking. This is used for arrays to only scan the currently used area of the allocation block. It also allows to easily change memory interpretation for large/small arrays which caused troubles in the other GC. For AAs this currently only skips the hash value, there is too little type information available to scan key and value precisely.
- compilation does not yet use the optimized trait (https://github.com/D-Programming-Language/dmd/pull/4192).

The druntime benchmark suite runs a few percent slower than the non-precise version, unless it hits false pointers. That doesn't seem to happen very often for the test suite, though.

### CODE REVIEW

**Comment by Orvid** [comment]
As far as bitmap compression goes, I will say that there is nothing as far as I know in the spec that prevents the compiler from re-ordering the fields of a non-decorated (non- `extern(C|C++|Windows|whatever)`) type.

**Comment by MartinNowak** [comment]
To summarize my points:
- False pointers are not an issue on 64-bit platforms.
- Precise GC isn't per se useful unless you figure out how to use it to improve marking speed.
  Take `ubyte[][]` as an extreme example, even though you only have to look at every 2nd word, you'll have a hard time to reach the same speed as a linear scan when encoding the mark pattern as metadata.
- Bitpatterns must be deduplicated and stored in a dense format, b/c marking is already completely bound by the speed of the memory bus.
- Indirect functions calls (type-specific mark functions) will cause plenty of code cache misses (b/c the jumps aren't predictable) and increase mark latency.
- Even w/ bigger types (more than the 64bytes of one cacheline) the prefetcher might get the next cacheline before you are able to figure out that you don't need to scan it.
- For types w/ very big internal buffers (`ubyte[4096] buf`) it'd be better to teach people, that using an external `ubyte[] buf = new ubyte[](4096)` is faster for the GC to mark.
- We should still invest some more time to separate data with points from NO_SCAN data, e.g. by separating data sections (see https://trello.com/c/Dsdxd1r3/56-ptr-data-section).

I think there are lower hanging fruits to speed up the GC, e.g. background/parallel finalization, vectorized (SIMD) loop in [mark](https://github.com/D-Programming-Language/druntime/blob/a83323439398a31126a33043bdd6c578bbc46433/src/gc/gc.d#L2022-L2027).

**Comment by andralex** [comment]
A few answers interspersed with as many questions (I'm not very familiar with the current implementation).

>Because the discussion came up again, a summary of my points:
>- False pointers are not an issue on 64-bit platforms.

Indeed I could not find much information about that. Searching for quoted "false pointers" yields little data (a subset of which points to discussions within the D community), because so few languages have them! I fear this might be a political issue - we're the only language that sticks with conservative GC when all other languages and systems use precise GCs and build upon them.

>- Precise GC isn't per se useful unless you figure out how to use it to improve marking speed.
  Take `ubyte[][]` as an extreme example, even though you only have to look at every 2nd word, you'll have a hard time to reach the same speed as a linear scan when encoding the mark pattern as metadata.

A more interesting case is structures with pointers on one cache line and no pointers on the next one. Consider:

```D
struct Customer {
    string lastname;
    string firstname;
    string address;
    string zipcode;
    int id;   
    char[8] ssn;
    ...
}
```

An array of `Customer` has 64 bytes worth or pointers per item and then some non-pointer data, say 64 bytes or more. In that case only a fraction of the cache lines need to be looked at. Would this save on scanning? How does that interact with prefetching? I'm not sure we can just make the blanket assumption that in all cases brute linear scanning wins.

Another question: what is the cost per word to decide whether it is a real pointer or a false pointer?

>- Bitpatterns must be deduplicated and stored in a dense format, b/c marking is already completely bound by the speed of the memory bus.

I agree bit patterns are not the best way to go about characterizing data shapes. We've discussed in the past the variant with generating a mark function per allocated type. So instead of bit patterns we have specialized code that knows how to scans types (and arrays thereof) transitively.

>- Indirect functions calls (type-specific mark functions) will cause plenty of code cache misses (b/c the jumps aren't predictable) and increase mark latency.

In the scheme sketched above, the only indirect calls are for roots. All others are direct calls because the functions are generated with full type information.

>- Even w/ bigger types (more than the 64bytes of one cacheline) the prefetcher might get the next cacheline before you are able to figure out that you don't need to scan it.

At some point surely prefetching will become slower than loading a fraction of the pages. I think we'd need to test this. Until then I think it's difficult to base decisions on it.

>- For types w/ very big internal buffers (`ubyte[4096] buf`) it'd be better to teach people, that using an external `ubyte[] buf = new ubyte[](4096)` is faster for the GC to mark.

Historically framing things as education issues are problematic. Also, often data schemata grow by accretion - one member here, one member there, and each member grows in size with adding features to the code. I don't think we can count this as a strong argument.

>- We should still invest some more time to separate data with points from NO_SCAN data, e.g. by separating data sections (see https://trello.com/c/Dsdxd1r3/56-ptr-data-section).

That'd be great indeed, but has a hard limit on what you can do. One theme in precise GC is that there are more levers to improving it than conservative.

>I think there are lower hanging fruits to speed up the GC, e.g. background/parallel finalization, vectorized (SIMD) loop in [mark](https://github.com/D-Programming-Language/druntime/blob/a83323439398a31126a33043bdd6c578bbc46433/src/gc/gc.d#L2022-L2027).

For the most part these don't compete with precision and would improve either approach.

**Comment by LightBender** [comment]
Erm, the point about false pointers is factually incorrect. While yes, in theory, a 64-bit address space should "solve" the false pointer problem, the reality is, as always, a little more complicated. There was a recent thread on the forum by someone doing big-data work. He ran into a false pointers problem in a 64-bit app. http://forum.dlang.org/thread/mafpzsuiuhzlriixymvy@forum.dlang.org

My guess is that the problem is that while the OS allocator *could* randomly map addresses inside the virtual address space, it is not. I strongly **suspect** that the behavior is more along the lines of: find free space in the physical memory then map the address to the next available block of contiguous free space in the virtual memory space. This would necessarily involve mostly filing up the 32-bit sized space before spilling over into 64-bit space.

As we move into an era of larger data-sets and the need to accurately work on them, I fear that the mantra of "64-bit solves false pointers!" is going to be proven false at an ever increasing rate.

**Comment by drbo** [comment]
A MAJOR win for precise or mostly-precise GC is the ability to compact all (resp. most) of the heap.  This eliminates (resp. dramatically reduces) fragmentation.

**Comment by drbo** [comment]
Also, the precise GC **has already been written** &ndash; it is probably a good idea to use it!

**Comment by rainers** [comment]
> False pointers are not an issue on 64-bit platforms.

I don't really buy this. Just adding std.datetime to the parsed files of the vdparser test shows a varying process memory usage of 400 to 900 MB for the x64 benchmark under win64 (address randomization is likely to cause more trouble than the usual addresses under linux). That doesn't happen with the precise GC.

I agree with most of what Andrei said, but this part:

> So instead of bit patterns we have specialized code that knows how to scans types (and arrays thereof) transitively. [...]
> In the scheme sketched above, the only indirect calls are for roots. All others are direct calls because the functions are generated with full type information.

I don't think transitivity works in D: it moves the memory type description from the allocation to the referrer, but that information is incomplete (a class reference doesn't know about derived classes) and ambiguous (multiple referers might use different pointer types, especially in system code). You have to keep the type information for every block anyway (in case it becomes a root), but tracking whether a transitive scan covered the actual allocation type seems duplicate effort.

Please note that the implementation in this PR is rather slow due to the number of indirections. Converting the scan function into CTFE generated code (making compilation even slower than the bitmap generation used to be before converting it into a trait) just reduces the number of indirections by one.

I still prefer https://github.com/D-Programming-Language/druntime/pull/1022, but it might need some optimizations for saving the pointer bitmap during allocation. Tuning these with dmd's weak optimizations was frustrating, though. Large arrays might use a simple scheme to save the pattern just once.

**Comment by andralex** [comment]
>I don't think transitivity works in D: it moves the memory type description from the allocation to the referrer, but that information is incomplete (a class reference doesn't know about derived classes) and ambiguous (multiple referers might use different pointer types, especially in system code).

Interesting re class references - so for classes you'd need an indirect call (including a hidden virtual method). Regarding storing different pointer types, what cases do you have in mind? For `void*` an indirect call would be needed, but otherwise I think we can assume fairly strict typing rules.

>You have to keep the type information for every block anyway (in case it becomes a root), but tracking whether a transitive scan covered the actual allocation type seems duplicate effort.

>Please note that the implementation in this PR is rather slow due to the number of indirections. Converting the scan function into CTFE generated code (making compilation even slower than the bitmap generation used to be before converting it into a trait) just reduces the number of indirections by one.

Couldn't that be significant?

**Comment by rainers** [comment]
> Regarding storing different pointer types, what cases do you have in mind? For void* an indirect call would be needed, but otherwise I think we can assume fairly strict typing rules.

The void* pointer was my main concern, too. Unions of different pointer types are similar. Most other pointer casts are just temporary and might only become a problem if the stack is scanned more precisely.

Other problems:
- how do you deal with internal pointers? With pointers to fields you cannot be sure that the referring type actually describes the full object.
- similar: slices might only refer to a part of an array, how do you keep track of which parts are already scanned?
- the AA implementation stores two objects (key + value) into one allocation. Currently, there is no proper type info for this pair, that's why it has to be dealt with at runtime.

**Comment by rainers** [comment]
>> just reduces the number of indirections by one. 
> Couldn't that be significant?

I'm not sure. IIRC it was also painful to have to call back into the GC to follow references. It could help if some of this can be inlined, but it would disallow swapping the GC without recompilation.

If there is interest, I can try to rebase this PR for some experiments.

**Comment by MartinNowak** [comment]
There is a huge difference between false pointers (as in random number pinning an array) and stale pointers on the stack/in registers. The latter being a real problem even for 64-bit, but this PR doesn't solve it.

> Another question: what is the cost per word to decide whether it is a real pointer or a false pointer?

Mostly a single comparison, https://github.com/D-Programming-Language/druntime/blob/a83323439398a31126a33043bdd6c578bbc46433/src/gc/gc.d#L2022-L2027.
The percentage of false pointers passing `p >= minAddr && p < maxAddr` was way below 1% when I tried to add a bloom filter to reduce false positives.
The 2nd hurdle (findPool) takes just a few cycles to find the exact pool.

> I agree bit patterns are not the best way to go about characterizing data shapes. We've discussed in the past the variant with generating a mark function per allocated type. So instead of bit patterns we have specialized code that knows how to scans types (and arrays thereof) transitively.

Well code will require even more memory than bit patterns, and required the same deduplication.
Given that pointers are 8-byte aligned bit pattern requires only 1-byte per 64-byte cacheline.

> For the most part these don't compete with precision and would improve either approach.

Yes, but we have limited resources, with which this does compete.

> My guess is ... necessarily involve mostly filing up the 32-bit sized space before spilling over into 64-bit space.

Let's please keep guesswork out of discussions, it's just wasting the time of everyone involved.

**Comment by MartinNowak** [comment]
> A MAJOR win for precise or mostly-precise GC is the ability to compact all (resp. most) of the heap. This eliminates (resp. dramatically reduces) fragmentation.

Yes, compaction is interesting. And fully solving the problem of precise register/stack marking makes this much more interesting. Just precise heap/root marking alone isn't that interesting.

**Comment by MartinNowak** [comment]
> An array of Customer has 64 bytes worth of pointers per item and then some non-pointer data, say 64 bytes or more. In that case only a fraction of the cache lines need to be looked at. Would this save on scanning? How does that interact with prefetching? I'm not sure we can just make the blanket assumption that in all cases brute linear scanning wins.

We certainly can't, but you can easily craft a benchmark to test this (https://github.com/D-Programming-Language/druntime/blob/a83323439398a31126a33043bdd6c578bbc46433/benchmark/gcbench/tree1.d). Also the question is not only what you win for some types, but how much you'd loose for others.

**Comment by drbo** [comment]
@MartinNowak JavaScriptCore and Steel Bank Common Lisp use a mostly-copying collector, where objects that are pointed to only by other heap objects (the vast majority) can be moved, while objects that are pointed to by registers or the stack are pinned.  This provides good performance in practice.  So precise heap/root marking is already a big win, even if the stack and roots are still marked conservatively.  This is also shown by the dramatic reduction in memory leaks on 32-bit systems.

Also, I think that fully precise GC might actually be feasible, at least for LDC.  LLVM already supports precise, moving collectors thanks to work done at Azul Systems, which is being used by [an LLVM backend for CoreCLR][1] that is intended to become production-quality at some point.  GDC and DMD will need more work, though, unless one wants to use a shadow stack (don't &ndash; slow).

**Comment by rainers** [comment]
Outdated and unlikely to perform reasonably fast, closing.

**Pull request closed without merging**
