### PR TITLE
Add shorthand aliases for primitive types

### PR DESCRIPTION
**Pull request by ryuukk**
I have them in a personal module, but i am tired of importing that module everywhere

I think having them in object.d is a nice idea, even though i'd like the language to support that out of the box like every other languages out there, but i don't know how to do that, unfortunately

### CODE REVIEW

**Review by ibuclaw — COMMENTED** [review]
What's the benefit? Users already know these are fixed sized types, that doesn't need to be made clearer.

**Comment by ryuukk** [comment]
> What's the benefit? Users already know these are fixed sized types, that doesn't need to be made clearer.

same benefits of

    alias string = immutable(char)[];

It's consistent, less typing, it is clear, and for people who want to learn the language, it's straight forward too, let's you add more types and follow same consistent scheme (cent, SIMD)

**Comment by dkorpel** [comment]
> i'd like the language to support that out of the box like every other languages out there

Not C, C#, C++ or Java.

> It's consistent, less typing, it is clear, and for people who want to learn the language

Walter has already explained why he's against it: https://forum.dlang.org/post/sq65vr$1huq$1@digitalmars.com

But even if the proposed names are better, introducing synonyms does not make the language easier, because it introduces the question which one to use.

> lets you add more types and follow same consistent scheme (cent, SIMD)

No, the current convention of [typeNN](https://dlang.org/spec/simd.html#core_simd) (e.g. `float4`) doesn't work with e.g.  `f32`, which results in `f324`.

**Comment by ryuukk** [comment]
> Not C, C#, C++ or Java.

They are dying languages

> Walter has already explained why he's against it

That doesn't mean he is right about it, we can disagree with him

> introducing synonyms does not make the language easier, because it introduces the question which one to use.

i can understand that

> No, the current convention of [typeNN](https://dlang.org/spec/simd.html#core_simd) (e.g. float4) doesn't work with e.g. f32, which results in f324.

    f32x4

**Comment by ryuukk** [comment]
Anyone else? i'd rather see this be closed asap if nobody wants it than stay open and me waiting for an opinion

**Comment by dkorpel** [comment]
I'm going to close this because I see no way this gets in like this.
- The existing names are well-established in D
- Walter prefers them over the proposed alternative
- We both agree that having multiple names is bad for everyone

If you still want to pursue this, maybe when ideas for D3 comes up or C/C++/C#/Java are not top 10 languages anymore, feel free to propose this again. I suggest to post in the newsgroup in that case, that's more visible than a pull request discussion.

**Pull request closed without merging**
