### PR TITLE
fix Issue 22774 - TraceInfo is gathered only once when throwing a Thr…

### PR DESCRIPTION
**Pull request by mkykadir**
…owable

Update `info` during every `throw`

### CODE REVIEW

**Comment by thewilsonator** [comment]
I think the fix for this should be in user code to set `t.info = null` if you want a new trace using the same throwable object.

**Comment by Geod24** [comment]
> I think the fix for this should be in user code [...]

Why would one want this behavior ?

**Comment by thewilsonator** [comment]
Unless the red in the CI is unrelated, then this break a whole lot of stuff.

**Comment by mkykadir** [comment]
> Unless the red in the CI is unrelated, then this break a whole lot of stuff.

Investigating this but generally time-out during fail-compilation tests (randomly); for example stuck at 
``` ... fail_compilation/test16116.d   -verrors=0 -m64  -fPIC ()```

**Comment by mkykadir** [comment]
OK, one of the causes that I could find is [this](https://github.com/dlang/druntime/blob/c6762914682d4fa894e2b746bf4bd9ce3ec9f7cb/src/core/exception.d#L419), this changeset conflicts with it

**Comment by kinke** [comment]
> > I think the fix for this should be in user code [...]
> 
> Why would one want this behavior ?

In C#, there's a difference between `throw;` (a rethrow with the same context) and `throw e;` (new context): https://stackoverflow.com/questions/730250/is-there-a-difference-between-throw-and-throw-ex

In D:
```
try { foo(); }
catch (Exception e) { logException(e); throw e; } // keep the existing TraceInfo!
```

**Pull request closed without merging**
