### PR TITLE
Fix confusing message on array cast failure.

### PR DESCRIPTION
**Pull request by schveiguy**
Still needs a bug report. First I want to see it pass CI, as I'm not sure if there's a test somewhere for this message.

### CODE REVIEW

**Comment by schveiguy** [comment]
OK, this is ready for review, bug report is written.

**Review by dkorpel — APPROVED** [review]

**Comment by schveiguy** [comment]
@MoonlightSentinel thanks I didn't know how to make a unittest with this. Obvious in hindsight!

**Comment by schveiguy** [comment]
@PetarKirov nice! I will update when at home.

**Comment by schveiguy** [comment]
@PetarKirov I left in the array length, as I still don't want the user to have to do too much math. But should be good now.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
