### PR TITLE
Add tests for dassert with 'in'

### PR DESCRIPTION
**Pull request by wilzbach**
Requires https://github.com/dlang/druntime/pull/2463 and https://github.com/dlang/dmd/pull/9264

### CODE REVIEW

**Comment by wilzbach** [comment]
Added the test to https://github.com/dlang/druntime/pull/2463

**Comment by jacob-carlborg** [comment]
Why a separate PR?

**Comment by jacob-carlborg** [comment]
I was a bit slow

**Comment by wilzbach** [comment]
Sorry for the spam, I didn't realize initially that I could do it in two PRs.

**Pull request closed without merging**
