### PR TITLE
Fix issue 22328: Specific D types are used instead of Windows type aliases

### PR DESCRIPTION
**Pull request by maxsamukha**
BOOL is int, not bool

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Thanks, can you create a bugzilla issue for this

**Comment by maxsamukha** [comment]
> Thanks, can you create a bugzilla issue for this

https://issues.dlang.org/show_bug.cgi?id=22328

**Comment by thewilsonator** [comment]
Thanks, now retitle the _commit_ message "Fix issue 22328: Specific D types are used instead of Windows type aliases"

**Review by CyberShadow — APPROVED** [review]

**Comment by maxhaton** [comment]
Rebase needed?

**Comment by maxsamukha** [comment]
Since 'bool x = DllMain...' becomes a conversion error, this might be an (extremely unlikely) breaking change.

**Comment by maxsamukha** [comment]
> Rebase needed?

Done

**Pull request merged**
