### PR TITLE
core.math: Re-enable disabled tests and update toPrec comment

### PR DESCRIPTION
**Pull request by ibuclaw**
This to follow the merge of dlang/dmd#10654.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Whats the status of this?

**Comment by ibuclaw** [comment]
One small blocker in #11026, ready for merge once that fix is in the compiler.

**Comment by ibuclaw** [comment]
@thewilsonator - Rebased, hopefully it'll pass now.

**Comment by ibuclaw** [comment]
But of course there's got to be some weird law that says assertions work when tested outside the module, but the same tests fail inside.

**Pull request merged**
