### PR TITLE
Split Thread into Thread implementation and common ThreadBase

### PR DESCRIPTION
**Pull request by denizzzka**
(Work in progress)

### CODE REVIEW

**Comment by UplinkCoder** [comment]
That's a lot of work ...
But what's the benefit?

**Comment by denizzzka** [comment]
> But what's the benefit?

To facilitate implementation of own version of Thread.

**Comment by UplinkCoder** [comment]
@denizzzka do you have that usecase currently?

**Comment by denizzzka** [comment]
https://github.com/denizzzka/d_c_arm_test/tree/threads

**Comment by UplinkCoder** [comment]
@denizzzka cool stuff.

**Comment by denizzzka** [comment]
squashed into #3135

**Comment by MoonlightSentinel** [comment]
You don't need to open multiple PRs, you can always squash/amend the history and force push your changes...

**Comment by denizzzka** [comment]
Yes, but in this "draft PR" are displayed passed and failed tests for each commit. This can help to debug such huge PR.

**Pull request closed without merging**
