### PR TITLE
`core.memory`: Make GC.[profile]stats safe/nothrow/nogc

### PR DESCRIPTION
**Pull request by Geod24**
Better reviewed commit-by-commit.

### CODE REVIEW

**Comment by Geod24** [comment]
I've seen this mentioned a few times, but I can't see how that would make more sense that no (de)allocation.
A more accurate wording, perhaps, would be: "Statically known to never cause a GC cycle to trigger".

**Comment by CyberShadow** [comment]
> I've seen this mentioned a few times, but I can't see how that would make more sense that no (de)allocation.

I think the intention is to be able to use a runtime without a GC. So, if the entire program is `@nogc`, one could make the statement that the program will not invoke any GC functions, and does not need to be linked to a GC.

**Comment by rainers** [comment]
> So, e.g. `GC.free` is not `@nogc`.

Take a look, `free` is marked `@nogc`. The attributes have been added rather erratically, e.g. `addrOf` and `sizeOf` are `@nogc` , but `query` is not.

With the loose definition of "do not run a collection" we could make any code `@nogc` by calling `GC.malloc` with a flag "do not collect". That would also be faster than C-malloc/free + addRoot/removeRoot.

Another definition I've seen is "does not leave garbage to be cleaned up later", but that is a bit harder to enforce, especially if you include `addRoot` or `addRange` into that.

**Review by rainers — APPROVED** [review]
LGTM

I think the prefix `B_` is no longer needed if there's always a `Bins.` before it anyway, but removing it doesn't work for the enumerators with numbers.. So better left it as is for now.

**Comment by CyberShadow** [comment]
> Take a look, `free` is marked `@nogc`

Right, not since https://github.com/dlang/druntime/pull/1962. 

> With the loose definition of "do not run a collection" we could make any code `@nogc` by calling `GC.malloc` with a flag "do not collect". That would also be faster than C-malloc/free + addRoot/removeRoot.

I agree, that doesn't seem like a very useful definition of `@nogc`. However, I think marking `GC.free` as `@nogc` wasn't a very useful change, and now we have a precedent that we unfortunately can't easily revert.

Two more use cases of `@nogc` is to steer clear of the global GC lock.

**Comment by schveiguy** [comment]
Kind of off topic, but my 2 cents: `@nogc` has use if it serves a purpose for users. In general, people want to avoid the problems that the GC brings, and that mostly entails stop-the-world collection. But can also reasonably be linked to taking the GC lock.

Honestly, the compiler really should just provide a generic `@noxyz` type feature where you can statically disable a certain set of functions, or functions that might call that certain set of functions. The only reason it's specific to the compiler is because the compiler uses the GC directly and bypasses some semantic checking. But if the compiler was better designed to lower its GC calls to hooks and obeyed the attributes after lowering, then we probably could define `@nogc` to mean whatever we really want by tagging the functions as expected.

**Comment by CyberShadow** [comment]
@schveiguy I think you're describing an effect system, like in Nim: https://nim-lang.org/docs/manual.html#effect-system

**Comment by Geod24** [comment]
If that's the only point of contention, I can remove the `@nogc`, as it's the least important.

For context, Ocean has a [`testNoAlloc` function](https://github.com/sociomantic-tsunami/ocean/blob/82171e4c4feb11df6919fa5657153e5b78ef2999/src/ocean/core/Test.d#L311-L342) which our team uses to ensure a certain expression would not allocate. Obviously using a `@nogc` unittest is better, but there are some context in which a `@nogc` `unittest` can't be used: A trivial example would be if the function throws a `new Exception` in case of error, another one is when a delegate is passed and the delegate is not annotated with `@nogc`.

So, why did I add `@nogc` to this function ? Besides the fact that my interpretation was "no cycle", I first looked into it when I tried to write a unittest for #3752 , which originally had a non-templated `toString`, causing me to use this pattern.
However, as explained in https://github.com/dlang/druntime/pull/3760 , this is no longer useful.

So, since `testNoAlloc` is a tool used in contexts where `@nogc` is not an option, being able to make `testNoAlloc` itself `@nogc` is of little benefit. Obviously this reasoning only covers my own use case, and other people might have a reason to have those functions `@nogc`.

**Comment by CyberShadow** [comment]
Thanks!

> being able to make `testNoAlloc` itself `@nogc`

How would that work, anyway? In the same way how `assertNotThrown` are `nothrow`?

**Comment by Geod24** [comment]
Actually... In `core.memory`, `profileStats` is already marked `@nogc`. However, in `gc/interface`, it is not.
I think we should get rid of the obvious duplication here, but it seems illogical to me to have `profileStats` `@nogc` but not `stats`.

**Comment by Geod24** [comment]
> How would that work, anyway? In the same way how assertNotThrown are `nothrow`?

Poor wording on my end. It would only work if the test was inlined (as I did in the unittest) or if the method was templated.

**Review by CyberShadow — APPROVED** [review]
Alright. Looking at [the spec](https://dlang.org/spec/function.html#nogc-functions), it currently says:

> No-GC functions are functions marked with the `@nogc` attribute. **Those functions do not allocate memory on the GC heap.** These operations are not allowed in No-GC functions: 

So, this change would be in-line in the spec (as useful as that definition is).

Should we decide to change that definition later, the change here should not pose a significant obstacle considering other functions like `free` and `profileStats` are `@nogc` already.

**Comment by Geod24** [comment]
Rebased

**Review by maxhaton — APPROVED** [review]
This LGTM, if it turns out to be not a good idea we change it back in the future - however my experience of @nogc in practice is that it's a guarantee about GC usage rather than a guarantee the presence of the GC (either literally in the binary or just a given part of a program's operation) so this change is useful. 

As well as that, I don't think we should be overly kind to definitions of D semantics that try to bend over backwards to unidiomatic D code. By this I mean that `@nogc` implying a program will compile without the GC linked into the binary seems strange to me, and overly accepting of fragmentation (which in itself is the result of a vicious cycle of people not being told what things really matter, but still)

**Pull request merged**
