### PR TITLE
Fix x86_64 calling convention for functions with D linkage

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Related to https://github.com/dlang/dmd/pull/13287 .

### CODE REVIEW

**Comment by ljmf00** [comment]
@RazvanN7 how can I fix this interdependency? There is probably a lot to fix tho, but one idea would be to build some manual runtime checks on the args registers to check correct calling convention and when the compiler PR is merged, remove them?

**Comment by RazvanN7** [comment]
@ljmf00 This is problematic. It seems that we need to merge these both at once. But this gives me some chills since we cannot test this properly using our CI infrastructure. I think that the path of least resistance would be to merge this one and then make sure that the dmd pr passes all of the tests. My reasoning is that the dmd pr has a bigger area of changes and therefore should be tested properly before merging. However, this means that the pipeline will be broken for quite some time.

Offtopic: Fingers crossed that maybe we will get the monorepo project going cc @PetarKirov .

**Comment by RazvanN7** [comment]
Hmm maybe we can temporarily disable the tests that use `atomicCompareExchangeStrongNoResult` and `atomicFetchAdd` ? Are there many?

**Comment by ljmf00** [comment]
> @ljmf00 This is problematic. It seems that we need to merge these both at once. But this gives me some chills since we cannot test this properly using our CI infrastructure. I think that the path of least resistance would be to merge this one and then make sure that the dmd pr passes all of the tests. My reasoning is that the dmd pr has a bigger area of changes and therefore should be tested properly before merging. However, this means that the pipeline will be broken for quite some time.
> 
> Offtopic: Fingers crossed that maybe we will get the monorepo project going cc @PetarKirov .

I can try to test this as much as possible locally, although testsuite fails on master on my machine for some specific tests. I have to check them and try to fix it to avoid problems. Another problem we should care is that intrinsics are relying on this calling convention thing, some of which, directly mapped to opcodes, e.g. `bts` from core.bitops. The signature of bts function doesn't match with the intrinsic, making it binary incompatible. We could have a module called `__intrinsics` and remap args there to avoid this. I think it is a really bad decision mapping intrinsics directly to end user calls.

**Comment by dkorpel** [comment]
How about introducing a new version condition, say, `version(D_reversedParametersAbi)`? That also allows user code to transition and keep compatibility with multiple dmd versions.

**Comment by kinke** [comment]
> how can I fix this interdependency?

Create same-named branches on the *upstream* repos. E.g., `fix-call-conv` branches on the DMD/druntime/Phobos repos. (Most) CI systems check out these branches then; Buildkite still needs https://github.com/dlang/ci/pull/452.

**Comment by ljmf00** [comment]
> How about introducing a new version condition, say, `version(D_reversedParametersAbi)`? That also allows user code to transition and keep compatibility with multiple dmd versions.

I would say, a version specific to DMD. It was never a thing on the specification but rather a vendor-specific issue (actually LDC does the same thing), so it is weird to specify that.

**Comment by ljmf00** [comment]
Ultimately, this atomic ops should be intrinsics, but I'm not willing to implement those on the DMD backend.

**Comment by Geod24** [comment]
@ljmf00 : Now you can re-submit against DMD without worrying about inter-dependency :)

**Pull request closed without merging**
