### PR TITLE
Add bindings for getifaddrs/freeifaddrs

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Auto-tester seems to be timing-out for some (probably unrelated) reason:
```
timelimit -t 90  generated/linux/debug/32/unittest/test_runner std.algorithm.internal
19.826s PASS debug32 std.regex.internal.tests
timelimit: sending warning signal 15
make[1]: *** [unittest/std/experimental/allocator/building_blocks/free_list.run] Error 143
make[1]: Leaving directory `/media/ephemeral0/sandbox/at-client/pull-2284797-Linux_32/phobos'
make: *** [unittest-debug] Error 2
```

But this from cybershadow's auto test seems more relevant:
```
../dmd/src/dmd -c -o- -version=CoreDdoc -version=StdDdoc -Df.prerelease-dummy.html \
  -Xfdocs-prerelease.json -I../phobos @.prerelease-files.txt
../druntime/src/core/sys/linux/ifaddrs.d(19): Error: module socket is in file 'core/stdc/posix/sys/socket.d' which cannot be read
```

**Comment by nemanja-boric-sociomantic** [comment]
Updated, thanks!

**Comment by leandro-lucarella-sociomantic** [comment]
cybershadow is still pretty much unhappy:
```
make[1]: Entering directory '/home/dtest/DAutoTest/work/repo/dmd/src'
no cpu specified, assuming X86
CC=c++ /tmp/.host_dmd-2.068.2/dmd2/linux/bin64/dmd -conf=/tmp/.host_dmd-2.068.2/dmd2/linux/bin64/dmd.conf -ofdmd -m64 -vtls -J. -J../res -L-lstdc++ -version=MARS -wi access.d aggregate.d aliasthis.d apply.d argtypes.d arrayop.d arraytypes.d attrib.d builtin.d canthrow.d clone.d complex.d cond.d constfold.d cppmangle.d ctfeexpr.d dcast.d dclass.d declaration.d delegatize.d denum.d dimport.d dinifile.d dinterpret.d dmacro.d dmangle.d dmodule.d doc.d dscope.d dstruct.d dsymbol.d dtemplate.d dversion.d entity.d errors.d escape.d expression.d func.d globals.d hdrgen.d id.d identifier.d impcnvtab.d imphint.d init.d inline.d intrange.d json.d lexer.d lib.d link.d mars.d mtype.d nogc.d nspace.d opover.d optimize.d parse.d sapply.d sideeffect.d statement.d staticassert.d target.d tokens.d traits.d utf.d visitor.d typinf.d utils.d statementsem.d safe.d objc_stubs.d libelf.d scanelf.d irstate.d toctype.d glue.d gluelayer.d todt.d tocsym.d toir.d dmsc.d tocvdebug.d s2ir.d toobj.d e2ir.d eh.d objc_glue_stubs.d backend/bcomplex.d backend/cc.d backend/cdef.d backend/cgcv.d backend/code.d backend/cv4.d backend/dt.d backend/el.d backend/global.d backend/obj.d backend/oper.d backend/outbuf.d backend/rtlsym.d backend/code_x86.d backend/ty.d backend/type.d backend/exh.d backend/mach.d backend/mscoff.d backend/dwarf.d tk/dlist.d root/aav.d root/array.d root/ctfloat.d root/file.d root/filename.d root/man.d root/outbuffer.d root/port.d root/response.d root/rmem.d root/rootobject.d root/speller.d root/stringtable.d newdelete.o glue.a backend.a
expression.d(10678): Error: found '<<' instead of statement
expression.d(10689): Error: declaration expected, not '=='
expression.d(10694): Error: declaration expected, not 'if'
expression.d(10697): Error: declaration expected, not 'if'
expression.d(10702): Error: unrecognized declaration
```

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, all PR we made recently say the same, so maybe is a problem with the auto-test itself or master?

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, looks like DAutoTest is generally flaky past few days.

**Comment by nemanja-boric-sociomantic** [comment]
Updated with changelog entry (not sure if it's all right, though).

**Pull request merged**
