### PR TITLE
Fix issue 20354: interface is not supported by cas

### PR DESCRIPTION
**Pull request by lempiji**
I want to fix this issue.
Some packages are breaking now. :cry:

https://issues.dlang.org/show_bug.cgi?id=20354

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
src\core\atomic.d(246): Error: undefined identifier `U`
src\core\atomic.d(830): Error: template instance `core.atomic.atomicExchange!(cast(MemoryOrder)5, Inter, shared(Inter))` error instantiating
src\core\atomic.d(910):        instantiated from here: `testXCHG!(shared(Inter))`
```

I think https://github.com/dlang/druntime/blob/master/src/core/atomic.d#L245-L246 is a typo.

CC @TurkeyMan git blames you for this

Should that be `alias Thunk = Unshared!V;`?

**Comment by thewilsonator** [comment]
Also as this is a regression, please target stable.

**Comment by PetarKirov** [comment]
I rebased the PR to stable and fixed the remaining errors.
@TurkeyMan can you take another look?

**Comment by thewilsonator** [comment]
LGTM

**Pull request merged**
