### PR TITLE
[minor/typo] Fix DragonFlyBSD typo in core/sys/posix/locale.d

### PR DESCRIPTION
**Pull request by dkgroot**
Simple typo:
Version(DragonflyBSD) -> Version(DragonFlyBSD)

### CODE REVIEW

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Comment by thewilsonator** [comment]
Hmm there seems to be some network problems?

**Comment by dkgroot** [comment]
Just wait and retry later ?

**Comment by thewilsonator** [comment]
Dunno, try giving it a force push.

**Comment by dkgroot** [comment]
Still don't understand why some tests expect/require network access :-)

**Pull request merged**
