### PR TITLE
Remove old adCmp code ( replaced by object.__cmp )

### PR DESCRIPTION
**Pull request by somzzz**
Cleanup.

This code is not used anymore. All array comaprisons are now done via ```object.__cmp```.
Last dmd call to this is removed here: https://github.com/dlang/dmd/pull/7279

### CODE REVIEW

**Comment by andralex** [comment]
This seems to not be called from within dmd, do gdc or ldc need it? cc @WalterBright @ibuclaw @klickverbot @redstar

**Comment by ibuclaw** [comment]
`_adCmp2` is still actively being used.  But I guess it won't be once recent switch patches have been backported.

**Comment by andralex** [comment]
@ibuclaw so what's the sequence of actions? Keep this on the backburner until you are done backporting?

**Comment by ZombineDev** [comment]
@kinke @JohanEngelen what's the situation like on the LDC side? Can we move forward with removing the old array comparison implementation?

**Comment by andralex** [comment]
@klickverbot thx

**Pull request merged**
