### PR TITLE
Fix Issue 21701 - casWeak is not implemented

### PR DESCRIPTION
**Pull request by rymrg**
dmd aliases casWeak to casStrong.

### CODE REVIEW

**Review by TurkeyMan — APPROVED** [review]

**Review by PetarKirov — APPROVED** [review]

**Comment by RazvanN7** [comment]
@rymrg please rebase this to get rid of the spurious failures.

**Comment by rymrg** [comment]
> @rymrg please rebase this to get rid of the spurious failures.

Last commit to stable is 4 days ago. #3396 hasn't been merged yet.

**Review by ibuclaw — CHANGES_REQUESTED** [review]
What about GDC and LDC?

**Comment by rymrg** [comment]
> What about GDC and LDC?

ldc has its own fork of druntime. So I planned to cherry pick and add the related code after this is merged. Where is druntime located for gdc?

**Comment by ibuclaw** [comment]
> > What about GDC and LDC?
> 
> ldc has its own fork of druntime. So I planned to cherry pick and add the related code after this is merged. Where is druntime located for gdc?

Same file as where you're editing here.

https://github.com/dlang/druntime/blob/bcf3ecc2463b6411aeb17037fc38175fba577053/src/core/internal/atomic.d#L856-L872

**Review by ibuclaw — APPROVED** [review]
OK

**Review by RazvanN7 — APPROVED** [review]

**Comment by rymrg** [comment]
@RazvanN7 I'm having hard time getting the rebase to work correctly.

**Comment by RazvanN7** [comment]
I normally do:

```
git checkout master
git pull
git checkout $branch
git rebase master
git push ...
```

**Pull request merged**
