### PR TITLE
add nothrow to windows files

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
blocking https://github.com/dlang/dmd/pull/13960

**Comment by dkorpel** [comment]
> blocking [dlang/dmd#13960](https://github.com/dlang/dmd/pull/13960)

Like mentioned in the other PR, this doesn't unblock dmd, because the newest DMD source needs to be compilable with 5 year old DMD as well.

**Comment by rainers** [comment]
This is ok just as adding `@nogc` was in the other PR, because the attributes are not applied to the interfaces. But that also means it doesn't unblock the dmd PR: calling `IUnknown.Release` is still not `nothrow` (BTW: some declarations in oleauto.d must also be nothrow).

If you desperately want to add the attributes while also compiling with older versions of dmd, you'll have to redeclare the interface and functions in vsoptions.d:
```
import core.sys.windows.com;
import core.sys.windows.wtypes : BSTR;
import core.sys.windows.basetyps;

nothrow:
extern (Windows) {
    // redeclared here to add attributes NOW
    interface IUnknown {
    nothrow:
        HRESULT QueryInterface(IID* riid, void** pvObject);
        ULONG AddRef();
        ULONG Release();
    }

    HRESULT CoCreateInstance(REFCLSID, IUnknown, DWORD, REFIID, PVOID*);
    void CoUninitialize();
    HRESULT CoInitialize(PVOID);
    void SysFreeString(BSTR);
    uint SysStringLen(BSTR);
}
```

**Comment by RazvanN7** [comment]
ping @WalterBright

**Review by rainers — APPROVED** [review]
These changes are ok and non-breaking, because they don't affect the interfaces.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
