### PR TITLE
add @system to posix interface

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Is this for DIP 1028? If so, would it make sense to wait until the discussion regarding what to do about `extern(C)` function finalizes?

Are library (binding) authors expected to follow suit?

**Comment by WalterBright** [comment]
> Is this for DIP 1028?

Yes.

> If so, would it make sense to wait until the discussion regarding what to do about extern(C) function finalizes?

It should be done regardless.

> Are library (binding) authors expected to follow suit?

Yes.

**Comment by WalterBright** [comment]
Hmm, this is a little strange:
```
compilable/testInference.d(287): Error: static assert:  `"extern (C) void function() @system" == "extern (C) void function()"` is false
```

**Comment by WalterBright** [comment]
Dang, I can't repro it locally.

**Pull request merged**
