### PR TITLE
Further improve cas functions

### PR DESCRIPTION
**Pull request by TurkeyMan**
Naked functions remove all the surrounding junk, and register utilisation matches calling convention.

Note: Not finished. I just need CI to run over it, and confirm the ABI is correct for all paltforms.

### CODE REVIEW

**Comment by thewilsonator** [comment]
OK ping me when its good.

**Comment by TurkeyMan** [comment]
Looks like a bug in the inline asm...


```D
asmtest.d
---------
    bool cas(byte*, byte*, byte)
    {
        asm pure nothrow @nogc @trusted
        {
            naked;
            mov AL, [RSI];
            lock; cmpxchg [RDX], DIL;
            mov DL, AL;
            setz AL;
            je skip_writeback;
            mov [RSI], DL;
        skip_writeback:
            ret;
        }
    }
````
Emits:
```asm
Disassembly of section .text._D7asmtest3casFPgQcgZb:

0000000000000000 <_D7asmtest3casFPgQcgZb>:
   0:   8a 06                   mov    (%rsi),%al
   2:   f0 0f b0 3a             lock cmpxchg %bh,(%rdx)
   6:   88 c2                   mov    %al,%dl
   8:   0f 94 c0                sete   %al
   b:   74 02                   je     f <_D7asmtest3casFPgQcgZb+0xf>
   d:   88 16                   mov    %dl,(%rsi)
   f:   c3                      retq
```
Note:
Src: `lock; cmpxchg [RDX], DIL;`
Output: `lock cmpxchg %bh,(%rdx)`

`DIL` turned into `%bh`... REX prefix missing?

**Comment by TurkeyMan** [comment]
Blocked by: https://issues.dlang.org/show_bug.cgi?id=20131

**Comment by TurkeyMan** [comment]
... I don't know what this new error is >_<

**Comment by TurkeyMan** [comment]
Actually, yes I do...

**Comment by TurkeyMan** [comment]
Okay. This is G2G when CI passes.
Shame I missed 2.088 by a few hours >_<

**Comment by TurkeyMan** [comment]
What's with that unit test? :/
Can that possibly be my fault?

**Comment by wilzbach** [comment]
unable to allocate memory. Unlikely. Let's see if it persists on that machine or was just a random failure.

**Pull request merged**
