### PR TITLE
Fix brace indentation in osthread.d

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Hmm, can you try rebasing to see if the error goes away?

**Comment by Geod24** [comment]
Re-triggering the CI should be enough (I just did that).

**Comment by lolgab** [comment]
Thank you for merging this PR. Was reading the code while I found this 😁

**Comment by lolgab** [comment]
Could you add the `hacktoberfest-accepted` label to this PR? :) Thanks :)

**Pull request merged**
