### PR TITLE
[uclibc] add aio defs

### PR DESCRIPTION
**Pull request by rracariu**
see https://github.com/coolshou/DIR-850L_A1/blob/master/rsdk-1.5.5-5281-EB-2.6.30-0.9.30.3-110714/config/uclibc/include/aio.h

### CODE REVIEW

**Comment by rracariu** [comment]
did a small rename `__glibc_reserved` to `__unused` as per header.

force pushed, but looks that circleci is DoA.

**Comment by thewilsonator** [comment]
> circleci is DoA.

Unfortunately yes.

**Comment by rracariu** [comment]
ping

**Comment by jacob-carlborg** [comment]
Please rebase to fix the CircleCI failure.

**Comment by rracariu** [comment]
Done, thanks!

**Comment by thewilsonator** [comment]
Auto merge added.

**Pull request merged**
