### PR TITLE
add nothrow and @nogc to windows files

### PR DESCRIPTION
**Pull request by WalterBright**
blocking https://github.com/dlang/dmd/pull/13960

### CODE REVIEW

**Comment by dkorpel** [comment]
This turns callback types nothrow nogc as well, which is a breaking change. That might be fine, but worth considering.

**Comment by rainers** [comment]
> This turns callback types nothrow nogc as well, which is a breaking change. That might be fine, but worth considering.

Yes, something to keep an eye on, but in this case the function types seem to be meant as types of the respected functions, e.g. to be used for casting the result of `GetProcAddress("DllGetClassObject")`.

The change in `unknwn.d` doesn't change the interfaces (which would be too restrictive for implementing classes), so that won't help making vsoptions.d `nothrow` in https://github.com/dlang/dmd/pull/13960.

**Comment by WalterBright** [comment]
https://devblogs.microsoft.com/oldnewthing/20200911-00/?p=104205 suggests that COM interfaces are nothrow. They're also designed to be used with C, which doesn't throw.

**Comment by rainers** [comment]
Indeed, the `STDMETHOD` macro contains `__declspec(nothrow)` by default (can be disabled with a preprocessor define), but the `IUnknown` interface doesn't include it. Adding it is probably intended, but will break code now because overriding methods are unllikely to be annotated.

Not allowing arbitrary allocations with `@nogc` is more restrictive, though.

**Comment by WalterBright** [comment]
@rainers what prompted this is I can't get dmd source code to be `nothrow` because some of it calls code in unknwn.d and vsoptions.d.

(Also, the AddRef and Release functions were designed before exception handling came about, and they obviously won't work with exceptions flying around.)

**Comment by rainers** [comment]
I understand what you are trying to do but

- the change here isn't good enough, you will have to add `nothrow @nogc:` inside the interface declarations, too.
- dmd is compiled with older versions, too, so it might take a while until the change is usable inside dmd

I forgot that attributes are inherited by overriding functions automatically, so that restricts breakage to implementations of these methods that call unannotated functions. I'm fine with updating my sources (though most use a different translation of the Windows headers anyway), but I suspect there will be some breakage.

**Comment by WalterBright** [comment]
I rebooted this as https://github.com/dlang/druntime/pull/3797

**Pull request closed without merging**
