### PR TITLE
fix Issue 21026 - add core.bitop.bswap(ushort)

### PR DESCRIPTION
**Pull request by WalterBright**
Prepare for adding this to the compiler as an intrinsic. It should generate an XCHG instruction.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Hmm, maybe `bswap16`, `bswapUshort`, `shortBswap` or something like that would have been better. Having `byteswap` and `bswap` with no obvious connection seems confusing.

(Not everyone knows x86's `bswap` instruction – to them, would reading a piece of code that uses both maybe suggest that `byteswap` swaps bytes and `bswap` swaps bits?)

**Comment by wilzbach** [comment]
There was a time when new symbols weren't merged within ten hours and with actual consideration about their name (as they are basically set in stone once released)...

**Comment by WalterBright** [comment]
I don't mind if you want to rename them to bswap16, bswap32, and bswap64. Those functions should have separate names because they don't overload nicely. (The original sin was when bswap(ulong) came along https://github.com/dlang/druntime/pull/1480)

> Not everyone knows x86's bswap instruction

Consider where the word "blitting" came from? It came from the PDP-10 instruction BLT which stood for "BLock Transfer". It gradually evolved into a word.

Anyhow, core.bitop has numerous functions named after their corresponding instructions https://dlang.org/phobos/core_bitop.html which is appropriate. It builds on a programmer's existing vocabulary.

**Comment by schveiguy** [comment]
I'm fine with bswap as a name. I can never imagine it being considered "bit swap", as I don't even know what that means or what you would do with it.

I think they should be renamed bswap16, bswap32, and bswap64, and deprecate bswap(ulong). bswap(uint) is probably fine to leave in there, as it's likely the most common one.

**Comment by dnadlinger** [comment]
> I'm fine with bswap as a name. I can never imagine it being considered "bit swap", as I don't even know what that means or what you would do with it.

I'm fine with `bswap` as well – it's perhaps a bit more obscure than necessary for people not that familiar with low-level stuff, but the name has been in `core.bitop` for a long time, so no need to have a discussion about it now.

What I do find potentially misleading is having both `byteswap` and `bswap`, the former suggesting by exclusion that `bswap` in fact doesn't swap bytes.

**Comment by n8sh** [comment]
>I think they should be renamed bswap16, bswap32, and bswap64, and deprecate bswap(ulong). bswap(uint) is probably fine to leave in there, as it's likely the most common one.

In my opinion the annoyance of asymmetrical naming between `bswap(uint)` / `bswap(ulong)` / `bswap16(ushort)` isn't sufficient justification to impose a maintenance burden on every program that has used `bswap(ulong)` in the 5 years it has existed in core.bitop.

**Pull request merged**
