### PR TITLE
Fix Issue 18924 - Use addition rather than XOR for order-independent hash combination

### PR DESCRIPTION
**Pull request by n8sh**
(for associative arrays)

### CODE REVIEW

**Comment by JinShil** [comment]
Why? What's motivating this?

**Comment by JinShil** [comment]
I don't want to blindly approve this.  Can you cite a technical whitepaper, or demonstrate an improvement with a benchmark?

**Comment by n8sh** [comment]
Here's a "benchmark". Let's say we're hashing sets of elements and each element has the same hash, with the lowest bit set to 1 and all other bits 0. If you combine the hashes with XOR, you get a parity bit. Every set will be hashed to either 0 or 1, which is bad news if we hope to minimize hash collisions. If you combine the hashes with addition the result is the length of the set, the low bit of which is identical to the result of combining the hashes with XOR.

**Comment by JinShil** [comment]
I'll defer to other reviewers who have more expertise in this area than I.

**Pull request merged**
