### PR TITLE
Clang std::string

### PR DESCRIPTION
**Pull request by TurkeyMan**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
There's a mangling issue that I can't isolate... :/

**Comment by thewilsonator** [comment]
For reference the issue is:
```
/tmp/string-abbbdd.o: In function `sumOfElements_val(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)':
src/string.cpp:(.text+0x197): undefined reference to `fromC_ref(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
src/string.cpp:(.text+0x1c6): undefined reference to `fromC_val(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
```

**Comment by TurkeyMan** [comment]
I can read the logs ;) ... but the issue is this:
`std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >`
See the `std::__1::basic_string`, `std::__1::char_traits`, and `std::__1::allocator`?
It should be `std::__1::basic_string`, `std::char_traits`, and `std::allocator`... and it's definitely written that way in the code.

I suspect perhaps an issue with the mangling exists where the outer template's namespace it being transitively applied to the template arguments or something, rather than those arguments being mangled with their own namespaces...
I can't reproduce that though, I have no system that can reproduce those build results... so I don't know how to test this.

**Comment by Geod24** [comment]
I can reproduce on my system. I'll take a look at it.

**Comment by TurkeyMan** [comment]
I think I spotted it; my libc++ reference was inconsistent with other material I've found on the net... I think those things SHOULD be mangled with `__1`. I've pushed that change, and we'll see if it links...

**Comment by Geod24** [comment]
If it's any help, the following runs on Mac: https://github.com/bpfkorea/agora/blob/v0.x.x/source/scpd/Cpp.d

And yeah `std::allocator` is in `__1`

**Comment by thewilsonator** [comment]
> I can read the logs ;)

It took me a while to find it ;) thats why I posted that.

**Comment by TurkeyMan** [comment]
@Geod24 If CI fails, can you grab this patch and see if you can see where I've fucked up the mangling?

**Comment by Geod24** [comment]
Looks like you won't be needing it :)

**Comment by TurkeyMan** [comment]
Oh my! Huzzah!

**Pull request merged**
