### PR TITLE
Factorise Thread and Fiber

### PR DESCRIPTION
**Pull request by thewilsonator**
Factor out the common code dealing with stack contexts and callable.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Hmm, @rainers any ideas why this would fail with `Unable to suspend thread`? I'm guessing its a GC pause.

**Comment by rainers** [comment]
> Hmm, @rainers any ideas why this would fail with `Unable to suspend thread`? I'm guessing its a GC pause.

Yes, it might be issued by thread_suspendAll. @thewilsonator Where do you see that error?

**Comment by thewilsonator** [comment]
```
Testing forkgc2
./generated/linux/debug/64/forkgc2 
2 unittests passed
Testing sigmaskgc
./generated/linux/debug/64/sigmaskgc 
2 unittests passed
Testing startbackgc
./generated/linux/debug/64/startbackgc 
Testing recoverfree
./generated/linux/debug/64/recoverfree 
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
2 unittests passed
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
uncaught exception
core.thread.osthread.ThreadError@src/core/thread/osthread.d(3021): Unable to suspend thread
----------------
```

**Comment by rainers** [comment]
> ./generated/linux/debug/64/forkgc2 
> 2 unittests passed

This looks suspicious: forkgc2 doesn't contain unittests, so I expect this is the output of other tests running in parallel? I would try disabling that for more consistent output.

**Comment by Geod24** [comment]
This module only includes internal declaration though, doesn't it ?

**Comment by thewilsonator** [comment]
I've decided to split this PR into something that won't have those suspension problems.

**Pull request merged**
