### PR TITLE
[dmd-cxx] fix Issue 19861 - core.cpuid reports the wrong number of threads

### PR DESCRIPTION
**Pull request by ibuclaw**
Backported from #2620

### CODE REVIEW

**Comment by ibuclaw** [comment]
Bootstrapped, running regression tests...

**Comment by Geod24** [comment]
Not backporting the tests ?

**Comment by ibuclaw** [comment]
What tests?

**Comment by ibuclaw** [comment]
> What tests?

It's just a bunch of printfs, nothing is actually checked.  So I don't honestly see the point of it.

**Comment by ibuclaw** [comment]
Regression tests ran, no reported failures.

**Pull request merged**
